aws-observability/aws-otel-java-instrumentation

awsagentprovider/build.gradle.kts
awsagentprovider/src/main/java/com/softwareaws/xray/opentelemetry/providers/AwsAgentProperties.java
awsagentprovider/src/main/java/com/softwareaws/xray/opentelemetry/providers/AwsTracerProviderFactory.java
awsagentprovider/src/main/resources/META-INF/services/io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.spi.TracerProviderFactory
awsagentprovider/src/main/resources/META-INF/services/io.opentelemetry.javaagent.spi.config.PropertySource
awsagentprovider/src/test/java/com/softwareaws/xray/opentelemetry/providers/AwsTracerProviderFactoryTest.java
dependencyManagement/build.gradle.kts
smoke-tests/runner/build.gradle.kts
smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/SpringBootSmokeTest.java

Updates agent dependency to 0.10.1 and uses `PropertySource` SPI instead of system property to interact properly with config property resolution order.
Default behavior of OTel changed from populating x-b3 to b3(single) when injecting (still extracts both)

Update to upstream agent 0.10.1

---

otelagent/build.gradle.kts

*Description of changes:* Upstream switched to Java 8 so no point in our bytecode targeting 7

Target java 8 for agent.

---

awsagentprovider/src/main/java/io/opentelemetry/sdk/trace/RandomIdGenerator.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerProviderFactory.java
awsagentprovider/src/main/resources/META-INF/services/io.opentelemetry.javaagent.shaded.io.opentelemetry.spi.trace.TracerProviderFactory
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerProviderFactoryTest.java
dependencyManagement/build.gradle.kts
sample-apps/spark/build.gradle.kts
sample-apps/spark/src/main/java/com/amazon/sampleapp/MetricEmitter.java
sample-apps/springboot/build.gradle.kts
sample-apps/springboot/src/main/java/com/amazon/sampleapp/MetricEmitter.java

Had to work around issue that prevents SPI configuration to work until 0.15.0. Fix is in upstream in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2077 but that has breaking changes to configuration options which we can't push out in a patch. This workaround is tame enough.

Update to OTel 0.14

---

build.gradle.kts
settings.gradle.kts

This is the successor to the gradle-nexus-staging-plugin we previously tried but couldn't due to conflicts with jib. It's modern code and doesn't conflict so we should finally be able to automate the nexus close.

Add publish-plugin

---

otelagent/build.gradle.kts

We currently append `-aws` to the version itself, but it makes it hard to release anything other than the agent from this repo (e.g. awsagentprovider as a separate jar, awspropagator). Release note titles also look a bit strange with the `-aws` suffix there.
This embeds `-aws` into the agent manifest directly instead, so we can still see the distro in `telemetry.auto.version`. Instead of having a patch version following the suffix (e.g. `-aws.1`), we can just make sure major / minor version stay in sync with upstream and not worry too much about the patch version since we'd only want to diverge in emergency cases either way.

Append aws suffix in agent manifest

---

dependencyManagement/build.gradle.kts
smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/SpringBootSmokeTest.java

Because of a dependency conflict between 1.4 and the 1.5 sdk-autoconfigure module (latter is still alpha API), this needs to be aligned for now. Didn't catch in unit tests due to a bad assertion.
Will release java-contrib 1.5 soon but we can release from SNAPSHOT in the meantime since it's not exposed through any POM

Update to xray sampler 1.5-SNAPSHOT

---

.github/workflows/main-build.yml
sample-apps/spark/build.gradle.kts
sample-apps/springboot/build.gradle.kts

Both of `springboot` and the `spark` app have containers with a `-test-` component in that last part of their image name.
https://github.com/aws-observability/aws-otel-java-instrumentation/blob/30f9f95629a71397b1ab90643f5b9d8bd133c241/sample-apps/springboot/build.gradle.kts#L18
https://github.com/aws-observability/aws-otel-java-instrumentation/blob/30f9f95629a71397b1ab90643f5b9d8bd133c241/sample-apps/spark/build.gradle.kts#L26
This PR adds it to the `spark-awssdkv1` app so that everything is consistent.

Remove `-test-` component for Sample App Images

---

sample-apps/spark-awssdkv1/src/main/java/com/amazon/sampleapp/MetricEmitter.java
sample-apps/spark/src/main/java/com/amazon/sampleapp/App.java
sample-apps/spark/src/main/java/com/amazon/sampleapp/MetricEmitter.java
sample-apps/springboot/src/main/java/com/amazon/sampleapp/DemoController.java
sample-apps/springboot/src/main/java/com/amazon/sampleapp/MetricEmitter.java

For the incoming Soak Tests, we would like to add an environment to control when the Sample Apps produces log outputs. We use branching to control the log messages that indicate an API endpoint was hit, and we remove the `System.out.println` log messages from the `MetricEmitter.java` file.

Add `SAMPLE_APP_LOG_LEVEL` env var to control sample app logging

---

.github/docker-performance-tests/docker-compose.yml
.github/workflows/soak-testing.yml

Fix authentication by using `aws sts get-session-token` instead of GitHub's `$ACTIONS_ID_TOKEN_REQUEST_URL` and `$ACTIONS_ID_TOKEN_REQUEST_TOKEN`. This is because we found that the GitHub OIDC token expires after 5 minutes, and Soak Tests might not refresh until 10 or 40 minutes later. That's why for Soak Tests specifically we need this different way of getting "short-lived credentials".
It would be interesting to check in the future if using `aws sts get-session-token` allow us to remove the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` secrets.

Use STS get-session-token for short lived AWS authentication with OIDC

---

.github/scripts/performance-tests/produce_metric_widget_images.py
.github/workflows/soak-testing.yml

Follow up to #84, we make some small edits to the Soak Tests:
1. Delete oldest snapshots in the `commits/<current_commit_id>/runs/` folder as well as the `commits/` folder.
2. Set the CPU threshold and Memory Threshold based on [this comment which found these values to work for all apps](https://github.com/NathanielRN/aws-otel-java-instrumentation/pull/1#issuecomment-925169660)
3. With https://github.com/JasonEtco/create-an-issue/pull/114 merged, we can use the upstream JasonEtco/create-an-issue action again! (This will be broken until the next minor release)
4. ~Fix authentication by using `aws sts get-session-token` instead of GitHub OIDC. This is because we found that the OIDC token expires after 5 minutes, and Soak Tests might not refresh until 10 or 40 minutes later. That's why for …

Small edits to Soak Tests

---

.github/workflows/soak-testing.yml

Follow up to #88, before we make a call to `aws sts get-session-token`, we need to have _some_ AWS credentials. We don't want the credentials to be long-lived, so we try to use the `AWS_WEB_IDENTITY_TOKEN_FILE` env variable resolution method to provide credentials. GitHub will populate this file with temporary credentials (that last 5 minutes) that will give us enough time to call `sts` for additional temporary credentials which last longer (24 hours).

Use GitHub OIDC Call to get AWS Creds before STS Call

---

.github/workflows/soak-testing.yml

In #88 and #89, we learned that there was _no way_ to get short-lived credentials for the Soak Tests.
If we use GitHub OIDC alone, the tokens expire after 5 minutes and credentials are unrecoverable if not refreshed within that time. Soak Tests run for 5 hours and at a collection interval of 10 minutes so they don't refresh in time.
If we use `aws sts get-session-token` we still need long lasting credentials. As mentioned in [the aws CLI docs](https://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html):
> The GetSessionToken operation must be called by using the long-term Amazon Web Services security credentials of the Amazon Web Services account root user or an IAM user.
Trying to use GitHub Sessional Credentials to get additional sessional STS credentials results in …

Use Long Lasting AWS Creds for Soak Tests only

---

.github/collector/docker-compose.yml
.github/workflows/docker-build-corretto-slim.yml
.github/workflows/docker-build-smoke-tests-fake-backend.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/patch-release-build.yml
.github/workflows/release-build.yml
.github/workflows/soak-testing.yml

N/A
GitHub just announced [their OIDC feature as GA](https://github.blog/changelog/2021-10-27-github-actions-secure-cloud-deployments-with-openid-connect/), but what’s even cooler is that they seem to have worked with the “configure-aws-credentials GH Action” team to integrate it seamlessly into the action :]
From the [aws-actions/configure-aws-credentials updated README](https://github.com/aws-actions/configure-aws-credentials#assuming-a-role) from 15 days ago:
> We recommend using GitHub’s OIDC provider to get short-lived credentials needed for your actions. Specifying role-to-assume without providing an aws-access-key-id  or a web-identity-token-file will signal to the action that you wish to use the OIDC provider. The default session …

Use aws-credentials action to configure creds bc it uses OIDC by default

---

.github/collector/docker-compose.yml
.github/workflows/docker-build-corretto-slim.yml
.github/workflows/docker-build-smoke-tests-fake-backend.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/patch-release-build.yml
.github/workflows/release-build.yml
.github/workflows/soak-testing.yml

Trying #110 again now that the action has released the changes as minor release to `v1`! In hindsight we could've tagged a commit on the https://github.com/aws-actions/configure-aws-credentials repository to have the changes right away, but this way we avoid the PR to move them all to be `@v1` again later.
I tested these changes on my fork, where I saw the `Configure AWS credentials` step succeed, but the test overall failed due to permissions needed to push to a public ECR repo. Here is a screenshot of the `main-build.yml` working, with the other workflows being very similar:
Soak Testing failed at first, but eventually worked when I added the `id-token: write` permissions to the workflow file:
Soak Test eventually ran again and succeeded after 5 hours: …

GH Action OIDC AWS Creds for GH workflows

---

.github/workflows/docker-build-corretto-slim.yml
.github/workflows/docker-build-smoke-tests-fake-backend.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/patch-release-build.yml
.github/workflows/release-build.yml

*Issue #, if available:* N/A
Following up with https://github.com/aws-observability/aws-otel-java-instrumentation/pull/130#discussion_r772858253, since we use GitHub OIDC to log in now, we should not need this sleep in our GH workflow. We used to do this because the AWS Creds GH action was in an alpha stage and failed without it. Now it is released and ready to be used.

Remove Sleep from Docker Corretto Workflow

---

sample-apps/spark-awssdkv1/build.gradle.kts
sample-apps/spark/build.gradle.kts
sample-apps/springboot/build.gradle.kts

This PR is to add the latest tag for spark-sample-app image and also to support the architecture arm64
expected image: `public.ecr.aws/aws-otel-test/aws-otel-java-spark:latest`

Adding latest tag and support arm64 architecture for the builds

---

dependencyManagement/build.gradle.kts

*Issue #, if available:* 
N/A
This is to update the Jackson library vulnerability. By updating the version, the databind nested dependency will be updated to version `2.13.2.1`, which will have fixed version.
Reference Link: https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom/2.13.2

Updating fasterxml jackson library to fix vulnerability

---

.github/CODEOWNERS

In the future perhaps there is a more appropriate team for this, but in the meantime it definitely shouldn't have me listed explicitly on it.

Use team for codeowners

---

smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/SpringBootSmokeTest.java

In [`v1.13.0`](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.13.0) of the upstream java sdk release the `instrumentLibrary` methods were deprecated and replaced by `InstrumentationScope`. In [`v1.14.0`](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.14.0) of the upstream sdk these deprecated methods were dropped. 

Remove deprecated instrumentLibrary method

---

awsagentprovider/build.gradle.kts
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAgentPropertiesCustomizerProvider.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerCustomizerProvider.java
awsagentprovider/src/main/resources/META-INF/services/io.opentelemetry.javaagent.extension.config.ConfigPropertySource
awsagentprovider/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerConfigurerTest.java

**Issue #, if available:** #203
Nightly builds started to fail after the Otel dependency was changed to v1.18.0. This happened because some APIs that were previously deprecated, were removed in that version.
This PR uses AutoConfigurationCustomizerProvider instead of deprecated APIs that were removed in the Upstream Otel v1.18

Fix nightly builds

---

dependencyManagement/build.gradle.kts

*Description of changes:* Updating dependencies and Otel Java version to 1.18
```
------------------------------------------------------------
:dependencyManagement Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest release version:
- com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.42.0
- com.google.guava:guava-bom:31.1-jre
- com.sparkjava:spark-core:2.9.4
- com.squareup.okhttp3:okhttp:4.10.0
- commons-logging:commons-logging:1.2
- org.assertj:assertj-core:3.23.1
- org.curioswitch.curiostack:protobuf-jackson:2.0.0
- org.springframework.boot:spring-boot-dependencies:2.7.3
- org.testcontainers:testcontainers-bom:1.17.3
The following dependencies have …
```

Update dependencies and Otel to v1.18.0

---

otelagent/build.gradle.kts

**IMPORTANT**: We should review the implications of this change before merging. DONT MERGE YET.
Solves #170
Changes the artifact that is resolved from a dependency created to `software.amazon.opentelemetry:aws-opentelemetry-agent` to the jar.

Publish to maven using pom with jar packaging

---

dependencyManagement/build.gradle.kts
settings.gradle.kts

**Description of changes:** Update dependencies to release v1.19.0
Obs.:
* org.slf4j 2.0.3 is backwards compatible with the last version published in the 1.x series. The only difference is that 2.0.3 requires Java 8.
* Updating jacksom-bom to 2.14.0-rc2 because it is only used in tests.

Update dependencies and Otel to v1.19.0

---

.github/workflows/pr-build.yml
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/software/amazon/adot/GradleUtils.kt
dependencyManagement/build.gradle.kts
gradle.properties
otelagent/build.gradle.kts
sample-apps/spark-awssdkv1/build.gradle.kts
sample-apps/spark/build.gradle.kts
sample-apps/springboot/build.gradle.kts
smoke-tests/runner/build.gradle.kts
smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/SpringBootSmokeTest.java
smoke-tests/spring-boot/build.gradle.kts

*Description of changes:* 
* Update jacksom bom to the latest stable version.
* Revert update in org.slf4j dependency. This was breaking integration tests because the test application stopped working as intended.
* Updated all tests and workflows to point to the registry `aws-otel-test`
* Create `integrationTests` task that is able to run locally exclusively so that the pr-build gh action can be idempotent. (previously it was depending on artifacts generated during the main-build gh action). This required adding some specific logic in the `jib` plugin because local docker daemon does not handle multiplatform images.

Cleanup for release v1.19.0

---

.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

Use us-west-2 region for publishing Github workflow metrics

Use us-west-2 region for publishing Github workflow metrics

---

.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/publish-status.yml

*Description of changes:* Use reusable workflow to publish status of other workflows. This will make it easier to have a central place for storing reusable workflows in the future as we will need to change just the name of the workflow while the parameters will remain the same.

Use reusable workflow to publish status

---

smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/LogInjectionTest.java

Fixes regex used in in log4j injection test because of changes made in PR #227 

Fix regex in log4j test

---

.github/actions/patch-dependencies/action.yml
.github/scripts/patch.sh
.github/workflows/main-build.yml
.github/workflows/pr-build.yml
.github/workflows/release-build.yml
RELEASING.md

**Description of changes:** Add process for creating patch releases that is able to patch opentelemetry dependencies.
The idea is to checkout the upstream dependencies, apply carefully created patches and publish these patched dependencies to maven local.

Add new process for patch releases

---

.github/actions/patch-dependencies/action.yml

*Description of changes:* Cleanup patch repositories after build so that we don't fail the validation of the release process. https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/4061415093/jobs/6991406741#step:8:71

Cleanup patch repositories after build

---

.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/patch-release-build.yml
.github/workflows/release-build.yml

- Separating the Build and Publish of artifacts in separate steps.
- Removing the latest tag
- Using new java-image-release role for pushing the jar image to public ecr.
- Updating nightly build workflow to push a jar image to integ-test account with nightly tag.
TODO:

Updating Release and Nightly build workflows

---

Dockerfile
tools/cp-utility/src/main.rs

*Description of changes:* The operator uses the command property for Init containers, which overrides the `ENTRYPOINT` the definition inside the docker image. 
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#entrypoint
https://github.com/open-telemetry/opentelemetry-operator/blob/20ea43a43bbe5ba4a512ffc7742a92d14cc3d7d9/pkg/instrumentation/javaagent.go#L71
This change makes the cp-utility behave exactly like the cp command, not requiring an `ENTRYPOINT` meaning that `cp` will not be an argument of the cp-utility anymore.
I simulated what the operator does end to end with the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: java-sample-app
namespace: java-sample-app
spec:
selector:
matchLabels:
app.kubernetes.io/name: java-sample-app …
```

Do not use entrypoint for cp-utility

---

Dockerfile

*Description of changes:* Change permissions of the java agent file to match the [upstream operator image. 
](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/java/Dockerfile#L13)
https://docs.docker.com/engine/reference/builder/#copy

Fix: Apply file permissions to match upstream operator image

---

.github/workflows/patch-release-build.yml
.github/workflows/release-build.yml

*Description of changes:* This will make sure that the name of the jar is exactly the same during the build for the the docker image and for maven central. 
If we did not make this change the docker step will fail, because it will not be able to find the artifact.

Fix: Make sure name of artifact is aligned in release workflow

---

dependencyManagement/build.gradle.kts

*Description of changes:* This has to be done manually because dependabot is trying to merge v2.15.1, but artifacts are still not available in maven central: https://github.com/aws-observability/aws-otel-java-instrumentation/pull/406

Update jackson-bom to 2.15.0

---

.github/workflows/codeql-analysis.yml

*Description of changes:* Update CodeQL according to https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

Update CodeQL version to 2.

---

.github/workflows/patch-release-build.yml
.github/workflows/release-build.yml

*Issue #, if available:* #398
*Description of changes:*  Remove the need for Node 12. The actions being removed are deprecated and can be replaced by github cli commands. 

Use GitHub cli to create release

---

.github/workflows/main-build.yml

PR to fix this error due to recent java_agent_e2e_operator testcase introduction to mainbuild workflow: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/5482566007/jobs/10001324855
changing var name to lowercase - to match it variable name in the eks testcase.

Fix mainbuild workflow

---

.github/workflows/main-build.yml

Fix main build workflow for release branch
There were space around the `=` in the script which caused a failure. this pr simplifies the process to get the name of the release branch in the test framework.

Fix main build workflow for release branch

---

.github/workflows/main-build.yml

The recent failures of this workflow (while merging series of dependabot PRs) looks like caused by multiple jobs of java-agent-main-build running at the same time: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/5550810364/jobs/10136412203#step:9:1450
We don't want the multiple EKS Operator tests to run on same cluster as same time, as Operator is installed on default namespace. To ensure this, adding concurrency group; and also setting `cancel-in-progress` job as false for this workflow. 

Java Agent Main Build: Setting concurrency group

---

awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerConfigurerTest.java
build.gradle.kts
dependencyManagement/build.gradle.kts
otelagent/build.gradle.kts
sample-apps/spark-awssdkv1/build.gradle.kts
sample-apps/spark-awssdkv1/src/main/java/com/amazon/sampleapp/MetricEmitter.java
sample-apps/spark/build.gradle.kts
sample-apps/spark/src/main/java/com/amazon/sampleapp/MetricEmitter.java
sample-apps/springboot/build.gradle.kts
sample-apps/springboot/src/main/java/com/amazon/sampleapp/MetricEmitter.java
settings.gradle.kts
smoke-tests/runner/build.gradle.kts
smoke-tests/spring-boot/build.gradle.kts

PR to Bump com.diffplug.spotless from 6.13.0 to 6.20.0 and resolve build error in this PR:  https://github.com/aws-observability/aws-otel-java-instrumentation/pull/496

Bump com.diffplug.spotless from 6.13.0 to 6.20.0 and Resolve build error

---

.github/workflows/main-build.yml

*Issue #, if available:* We require terraform version 1.5 to use `strcontains` function. 

Bump terraform version

---

otelagent/build.gradle.kts

*Description of changes:* [This commit](https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/3b77cc4b2de90ca821d53234e76ea8f279cfc34f) removed the semantic convention package from the Java agent. Therefore we need to include this dependency from our side.
If we don't do this, we get this error:
```
OpenTelemetry Javaagent failed to start
java.lang.NoClassDefFoundError: io/opentelemetry/javaagent/shaded/io/opentelemetry/semconv/resource/attributes/ResourceAttributes
at io.opentelemetry.contrib.aws.resource.Ec2Resource.buildResource(Ec2Resource.java:81)
at io.opentelemetry.contrib.aws.resource.Ec2Resource.buildResource(Ec2Resource.java:49)
at io.opentelemetry.contrib.aws.resource.Ec2Resource.<clinit>(Ec2Resource.java:35)
at …
```

Don't exclude semantic conventions package from shaded dependencies

---

.github/workflows/testcases.json

https://github.com/aws-observability/aws-otel-java-instrumentation/issues/570
Removing versions 23 and 26
and updating to versions 24 and 27

Updating e2e cluster versions

---

testing/sample-apps/springboot-remote-service/build.gradle.kts
testing/sample-apps/springboot/build.gradle.kts

jib build is failing on local as ECR_IMAGE_LINK>:<TAG> do not have a value. 

Fix release error testing in e2e testing sample apps

---

appsignals-tests/images/aws-sdk/aws-sdk-v1/build.gradle.kts
appsignals-tests/images/aws-sdk/aws-sdk-v2/build.gradle.kts
appsignals-tests/images/grpc/grpc-client/build.gradle.kts
appsignals-tests/images/grpc/grpc-server/build.gradle.kts
appsignals-tests/images/http-clients/apache-http-client/build.gradle.kts
appsignals-tests/images/http-clients/native-http-client/build.gradle.kts
appsignals-tests/images/http-clients/netty-http-client/build.gradle.kts
appsignals-tests/images/http-clients/spring-mvc-client/build.gradle.kts
appsignals-tests/images/http-servers/netty-server/build.gradle.kts
appsignals-tests/images/http-servers/spring-mvc/build.gradle.kts
appsignals-tests/images/http-servers/tomcat/build.gradle.kts
appsignals-tests/images/jdbc/build.gradle.kts
appsignals-tests/images/kafka/kafka-consumers/build.gradle.kts
appsignals-tests/images/kafka/kafka-producers/build.gradle.kts
appsignals-tests/images/mock-collector/build.gradle.kts

Fix jib build error in Contract Tests

Fix jib build error in Contract Tests

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAppSignalsCustomizerProvider.java

The functionality should be explicitly opt-in.

Fix default value for when the otel.smp.enabled property is not set

---

appsignals-tests/contract-tests/build.gradle.kts
appsignals-tests/images/grpc/grpc-base/build.gradle.kts
appsignals-tests/images/grpc/grpc-client/build.gradle.kts
appsignals-tests/images/grpc/grpc-server/build.gradle.kts
appsignals-tests/images/http-servers/netty-server/build.gradle.kts
appsignals-tests/images/kafka/kafka-consumers/build.gradle.kts
appsignals-tests/images/kafka/kafka-producers/build.gradle.kts
testing/sample-apps/springboot-remote-service/build.gradle.kts
testing/sample-apps/springboot/build.gradle.kts
testing/validator/build.gradle.kts

Adding changes to remove nightly-build-error in Contract and E2E Testing

Adding changes to remove nightly-build-error

---

testing/validator/src/main/java/com/amazon/aoc/services/XRayService.java
testing/validator/src/main/java/com/amazon/aoc/validators/TraceValidator.java

Issue:
There are occasional errors in the E2E testing when the EKS and EC2 tests run simultaneously. Sometimes one of the tests may retrieve traces generated by the /client-call API from the other test.
Description of changes:
The /client-call trace validator now filters retrieved trace with `aws_local_service = serviceName` and `aws_local_service = "local_root_client_call"`. Since each test run has a unique service name, this will ensure that the trace retrieved is specific towards the test being run.

Fix trace validation bug

---

testing/terraform/ec2/main.tf

Copy of PR to private repo.
Tested EC2 canary still passes and that the instances created by the test have IMDSv2 marked as `Required`.

E2E Test: Ensure the use of IMDSv2 in EC2 instances

---

.github/workflows/appsignals-e2e-ec2-canary-test.yml
.github/workflows/appsignals-e2e-ec2-test.yml
.github/workflows/appsignals-e2e-eks-canary-test.yml
.github/workflows/appsignals-e2e-eks-test.yml
testing/terraform/ec2/main.tf
testing/terraform/ec2/output.tf
testing/terraform/eks/main.tf
testing/terraform/eks/variables.tf
testing/validator/src/main/java/com/amazon/aoc/App.java
testing/validator/src/main/java/com/amazon/aoc/models/Context.java
testing/validator/src/main/resources/expected-data-template/ec2/aws-sdk-call-trace.mustache
testing/validator/src/main/resources/expected-data-template/ec2/client-call-trace.mustache
testing/validator/src/main/resources/expected-data-template/ec2/outgoing-http-call-trace.mustache
testing/validator/src/main/resources/expected-data-template/ec2/remote-service-trace.mustache
testing/validator/src/main/resources/expected-data-template/eks/aws-sdk-call-log.mustache
testing/validator/src/main/resources/expected-data-template/eks/aws-sdk-call-metric.mustache
testing/validator/src/main/resources/expected-data-template/eks/aws-sdk-call-trace.mustache
testing/validator/src/main/resources/expected-data-template/eks/client-call-log.mustache
testing/validator/src/main/resources/expected-data-template/eks/client-call-metric.mustache
testing/validator/src/main/resources/expected-data-template/eks/client-call-trace.mustache
testing/validator/src/main/resources/expected-data-template/eks/outgoing-http-call-log.mustache
testing/validator/src/main/resources/expected-data-template/eks/outgoing-http-call-metric.mustache
testing/validator/src/main/resources/expected-data-template/eks/outgoing-http-call-trace.mustache
testing/validator/src/main/resources/expected-data-template/eks/remote-service-log.mustache
testing/validator/src/main/resources/expected-data-template/eks/remote-service-metric.mustache
testing/validator/src/main/resources/expected-data-template/eks/remote-service-trace.mustache

The main goal of this PR is to add the E2E canaries to the following regions: CMH, DUB, NRT, SYD.
Also includes minor additional changes to the code.
- Added region as input to workflow
- Add region to test ID so that runs make different service accounts
- Change the validator input variable `--cluster` to `--platformInfo` to use one variable for platform specific information rather than making multiple for each platform. 
- Look for the most recent AMI for EC2 instances. 

Add e2e canary to public preview regions

---

testing/validator/src/main/java/com/amazon/aoc/services/XRayService.java

Follow up on this https://github.com/aws-observability/aws-otel-java-instrumentation/pull/617.
The previous PR applied two separate filter expressions while searching for xray traces, which returned any traces matching either conditions. Need to change the logic so that traces matching both conditions are returned.
Combined the two filter expressions into one.

Fix trace validation error follow up fix

---

.github/workflows/appsignals-e2e-eks-test.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

Current [workflows are failing](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/7176507664) and are not valid. Provide `aws-region` for the e2e test in worklow

Provide aws-region for the e2e test in worklow

---

.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

Adding concurrency tag to test in main build and nightly build without having conflicting jobs occurring at the same time. This way, the e2e-adot-test cluster will not be used by two jobs at the same time

E2E Testing: Add concurrency tag to test in main build and nightly build

---

.github/workflows/appsignals-e2e-eks-test.yml

The EKS Canary occasionally fails due to transitivity issues. One of the recurring errors are `Max attempts reached` in the  [step](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/7095916355/job/19313588479) : `Wait for Endpoint to Come Online`. This occurs due to the endpoint sometimes taking longer than expected to become ready. 
- Change the endpoint wait time from 5 minutes to 10 minutes. 
- Add a retry mechanism such that if either the terraform deployment or the endpoint connection fails, then destroy the terraform deployment and try again. This will ensure that the endpoint is deleted and recreated. 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Add Retry Mechanism to E2E EKS Terraform Deployment

---

.github/workflows/appsignals-e2e-ec2-test.yml
.github/workflows/appsignals-e2e-eks-test.yml

Issue #, if available:
The EC2 Canary occasionally fails due to transitivity issues. Some of the recurring errors are `Max attempts reached` in the [Step](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/7082260691/job/19272772682) : `Wait for Endpoint to Come Online` and the [Step](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/7115409391/job/19371495221): `Timeout while waiting for state to become running`. This occurs due to the endpoint and the ec2 instances sometime taking longer than expected to become ready.
Description of changes:
- Change the endpoint wait time from 5 minutes to 10 minutes.
- Add a retry mechanism such that if either the terraform deployment or the endpoint connection fails, then destroy the …

Add Retry Mechanism to E2E EC2 Terraform Deployment

---

.github/workflows/appsignals-e2e-eks-test.yml

The App Signals download directory was changed to testing/terraform/eks in this PR: https://github.com/aws-observability/aws-otel-java-instrumentation/pull/634
Need to run ./clean-app-signals.sh in the correct directory else the E2E EKS canary will fail to cleanup properly: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/7203256881

Change App Signals Directory for E2E EKS Testing

---

awsagentprovider/build.gradle.kts

fixed https://github.com/aws-observability/aws-otel-java-instrumentation/issues/648, https://github.com/aws-observability/aws-otel-java-instrumentation/issues/644 in v1.31.x.
In this PR, we changed the dependency configuration of `io.opentelemetry:opentelemetry-exporter-otlp` from `implementation` to `compileOnly`.
The high cardinality issue was caused by introducing this dependency as `implementation` which causes classpath conflict during the runtime.

[v1.31.1] [Cherry-pick 651] Change dependency config in awsagentprovider

---

awsagentprovider/build.gradle.kts

fixed https://github.com/aws-observability/aws-otel-java-instrumentation/issues/648, https://github.com/aws-observability/aws-otel-java-instrumentation/issues/644
In this PR, we changed the dependency configuration of `io.opentelemetry:opentelemetry-exporter-otlp` from `implementation` to `compileOnly`.
The high cardinality issue was caused by introducing this dependency as `implementation` which causes classpath conflict during the runtime.

Change dependency config in awsagentprovider

---

.github/workflows/appsignals-e2e-eks-test.yml

This change checks if there is an adot image passed to the workflow and patches the App Signals deployment to update the image and restarts the cloudwatch pods. We check for input instead of a specific workflow, allowing any workflow to call this and run the e2e test.
Note: It is a limitation of EKS addon that we cannot set the artifact version before enabling pulse because the enablement script refers to a specific version of the addon we cannot change/create a new one for. As such, we need to apply the change for the ADOT image after enabling app signals, then restart the relevant pods.
Tested in private repo:
Test showing failure when using a non application signals image: [run](https://github.com/aws-observability/aws-apm-java-instrumentation/actions/runs/7201809370)
- …

E2E Testing: Fix EKS test candidate image override

---

.github/workflows/appsignals-e2e-eks-test.yml

Allowing more time for the CW agent pods to be ready and including it in the retry mechanism of the workflow.

E2E Testing: Add failure in waiting for pods to retry mechanism

---

.github/workflows/appsignals-e2e-eks-test.yml

Reverts aws-observability/aws-otel-java-instrumentation#659
It's causing canaries to fail.
```
syntax error near unexpected token `fi'
Error: Process completed with exit code 2.
```

Revert "E2E Testing: Add failure in waiting for pods to retry mechanism"

---

.github/workflows/appsignals-e2e-eks-test.yml

Restore cache in AppSignals e2e to resolve [this](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/7266704488/job/19799965604#step:19:83) build failure.

Restore Cache in AppSignals e2e Tests Workflow

---

.github/workflows/release-build.yml

Publish the the ADOT Java image to a private ECR repository as well.
This PR makes use of this feature: https://docs.docker.com/build/ci/github-actions/push-multi-registries/

Feat: add support to releasing to private ECR

---

.github/actions/patch-dependencies/action.yml
.github/scripts/patch.sh
.github/workflows/main-build.yml
.github/workflows/pr-build.yml

Removing patch dependencies scope restriction to release branch only

---

.github/workflows/build-and-push-image-with-cpUtility-test.yml
.github/workflows/contract-tests.yml
.github/workflows/e2e-tests-app-with-java-agent.yml
.github/workflows/e2e-tests-with-embedded-java-agent.yml
.github/workflows/e2e-tests-with-operator.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

nightly-build workfow update

---

.github/actions/patch-dependencies/action.yml

*Issue #, if available:* Handle key and secret being multi-line strings using official [docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings). Use randomization suggested [here](https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully) to avoid EOF conflicts. 

Handle multi-line strings in patch action. 

---

.github/actions/cpUtility-testing/action.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

*Description of changes:* Composite actions do not have access to secrets. They must be passed in as inputs. 

Use input rather than secret in composite action

---

.github/workflows/appsignals-e2e-ec2-test.yml
.github/workflows/appsignals-e2e-eks-test.yml
.github/workflows/e2e-tests-app-with-java-agent.yml
.github/workflows/e2e-tests-with-operator.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

*Description of changes:* Refactor main build workflow to use env var directly. Also remove usage of setting DEFAULT_REGION env var in favor of just using input variable.

Fix usage of input variable in workflows

---

.github/workflows/codeql-analysis.yml

*Issue #, if available:* If a patch exists it must also be built in codeql workflow for successful workflow execution. 

Build patched artifacts in codeql workflow

---

.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

You cannot use env vars in the context of reusable workflow inputs. The env var must first be set as an output for a previous job. 

Set default region as build output

---

.github/workflows/codeql-analysis.yml

`
Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.15.5/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14567 /home/runner/work/_temp/codeql_databases/java". Exit code was 32 and last log line was: CodeQL detected code written in Java/Kotlin and Java/Kotlin but could not process any of it. Review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . See the logs for more details.
`
To address error we are reordering codeql initialization action to happen before patch build. 
https://github.com/orgs/community/discussions/68044#discussioncomment-7101451

reorder codeql init

---

.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

*Issue #, if available:* Missing `outputs` context identifier

add outputs context for default region var

---

.github/workflows/appsignals-e2e-ec2-test.yml
.github/workflows/appsignals-e2e-eks-test.yml
.github/workflows/e2e-tests-app-with-java-agent.yml
.github/workflows/e2e-tests-with-operator.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml

*Description of changes:* Revert the changes to `AWS_DEFAULT_REGION` env var that were made #703. The presence of the env var is required for some steps inside the workflows. This is not redundant and is required to be present in the env. 
This PR also moves the setting of the default region output to an explicit job. Previously it was done at the end of the build step. This caused `us-west-2` to be output because the composite `cpUtility` test action overrode that default value. Using an explicit job here will ensure that `us-east-1` value is used as the output every time. 

Reinsert aws default region env var

---

.github/workflows/e2e-tests-with-operator.yml
sample-apps/spark/build.gradle.kts

*Description of changes:* Add dependency to build spark sample app to `jibBuildWithoutAgent`.

Build before publishing in e2e operator tests

---

testing/terraform/ec2/main.tf

A new AMI available to the public that was matching our filter conditions for EC2 Terraform came pre-installed with Java 8. This caused dependency issues with the sample app which uses Java 11 used for E2E testing and caused the canary to fail. 
Added additional filter conditions for the EC2 AMIs to look for minimal images. Also updated the instances to install `java-11-amazon-coretto`
Test run:
us-east-1: https://github.com/harrryr/aws-otel-java-instrumentation/actions/runs/7495423753
us-east-2: https://github.com/harrryr/aws-otel-java-instrumentation/actions/runs/7495550565
eu-west-1: https://github.com/harrryr/aws-otel-java-instrumentation/actions/runs/7495547623
ap-norhteast-1: …

Change terraform to use minimal ami

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/base/ContractTestBase.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAppSignalsCustomizerProvider.java

SMP is just a component of Application Signals, so it makes sense that we appropriately name the config that controls the Application Signals.
Also, `http://cloudwatch-agent.amazon-cloudwatch:4317` as default exporter endpoint doesn't really work since it points to CW pod in EKS environment. Plus `4317` is also wrong as we have switched to `4315` for AppSignals.
*Testing*
Tested without and with updating the environment variables in contract tests to ensure the change is backward compatible.
- Test run with SMP config: https://github.com/srprash/aws-otel-java-instrumentation/actions/runs/7836933969/job/21386408375?pr=1
- Test run with AppSignal config: https://github.com/srprash/aws-otel-java-instrumentation/actions/runs/7837485201/job/21387233082?pr=1 
By …

Rename AppSignals configs with backward compatibility

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java

Updated generateRemoteService to parse HTTP_URL as last resort in case NET_PEER_NAME or NET_SOCK_PEER_ADDR are not present as attributes. If HTTP_URL is present, this will attempt to parse it and if it fails, it defaults to UNKNOWN_REMOTE_SERVICE.
Tested by updating the unit tests and verifying the expected behavior. 

Updated generateRemoteService to parse HTTP_URL as last resort

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAppSignalsCustomizerProvider.java

The SMP exporter for AppSignals metrics only support grpc transport protocol
SMP exporter transport protocol is configurable, follows OTel environment variables priority:
1. OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
2. OTEL_EXPORTER_OTLP_PROTOCOL
For example, 
customer can use grpc for traces and http/protobuf for AppSignals metrics:
```
OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4315 OTEL_METRICS_EXPORTER=none OTEL_SMP_ENABLED=true OTEL_AWS_SMP_EXPORTER_ENDPOINT=http://localhost:4316/v1/metrics java -javaagent:aws-opentelemetry-agent-1.32.0-SNAPSHOT.jar -jar ./build/libs/spring-boot-0.0.1-SNAPSHOT.jar Application
```
or use http/protobuf for both …

Support AppSignals metrics transport protocol configuration

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/v1/AwsSdkV1Test.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java

A follow up on this PR, where we left out the AWS SDK v1 instrumentation.
https://github.com/aws-observability/aws-apm-java-instrumentation/pull/160
Now with this change, for any version of AWS SDK client, we will be prefixing `AWS.SDK.` to the `RemoteService` attribute for the generated AppSignals metrics.

prefix `AWS.SDK` to the RemoteService from AWS SDK v1 spans

---

testing/validator/src/main/resources/expected-data-template/ec2/aws-sdk-call-metric.mustache
testing/validator/src/main/resources/expected-data-template/ec2/aws-sdk-call-trace.mustache

The e2e test in main-build is currently failing due to outdated remote target value for aws-sdk-call
Update the remote target value to ::s3:::e2e-test-bucket-name

Update RemoteTarget Value on E2E EC2 Test

---

testing/validator/src/main/resources/expected-data-template/eks/aws-sdk-call-metric.mustache
testing/validator/src/main/resources/expected-data-template/eks/aws-sdk-call-trace.mustache

Follow up from the https://github.com/aws-observability/aws-otel-java-instrumentation/pull/757 where EKS E2E test templates were missed out.

update the remote target for eks e2e validations

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/base/AwsSdkBaseTest.java

Followup contract test improvement following from https://github.com/aws-observability/aws-otel-java-instrumentation/pull/756
Testing done: PR workflow covers contract tests and is sufficient.

Add `RPC_SYSTEM` testing to AWS SDK contract tests

---

.github/workflows/appsignals-e2e-eks-test.yml

Based on changes introduced by this PR in the operator repo: https://github.com/aws/amazon-cloudwatch-agent-operator/pull/85
Validated [here](https://github.com/aws-observability/aws-application-signals-test-framework/actions/runs/8638684079) (note: this workflow failed as it is a WIP but the [ADOT image logging step](https://github.com/aws-observability/aws-application-signals-test-framework/actions/runs/8638684079) shows it has changed)

[E2E] Update patch command to let ADOT image update

---

.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/patch-release-build.yml
.github/workflows/release-build.yml
RELEASING.md
build.gradle.kts

Utilizes tokens created in NXRM rather than standard usernames and passwords. 
Secrets have already been added to the repository
https://central.sonatype.org/publish/generate-token/

Switch to using sonatype token user name and password

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAppSignalsCustomizerProvider.java

Updating Java Instrumentation to match parity with the Python Instrumentation. Update code based on this [change](https://github.com/aws-observability/aws-otel-python-instrumentation/commit/2301739fa32386b110197da28f1ce7fe9e4bbe86). 
The python instrumentation has strict dependencies on the python version for `grpc`, so `opentelemetry-exporter-otlp-proto-grpc` is only installed if explicitly called by the user. Such issues are not present in the Java instrumentation, so will leave the build configuration as it is. 
Only changes to be made are to update the endpoints for HTTP and grpc protocol
HTTP and grpc protocol will have different endpoints. 
By submitting this pull request, I confirm that my contribution is made under the terms of …

Add different endpoints for GRPC and HTTP protocal

---

.github/workflows/appsignals-e2e-ec2-test.yml
.github/workflows/appsignals-e2e-eks-test.yml

The Enablement E2E tests are failing during main-build. There are currently three issues:
- Parameter in the validators was changed and invalid now.
- The framework repository is not yet updated to reflect the new ADOT changes
- EKS sample app pods does not start properly. Suspect the secrets to the ECR containing sample app images are pointintg to the wrong address. 
- Update the request-body parameter with the query string parameter based on changes from this [PR](https://github.com/aws-observability/aws-application-signals-test-framework/commit/22d1f72a6468935217f9c1d868672a1de3cf17b5)
- Retrieve validation resources from the [framework](https://github.com/aws-observability/aws-application-signals-test-framework) repository …

Update Release Testing with Latest Update

---

.github/workflows/pr-build.yml
settings.gradle.kts

The e2e-operator-test is currently failing in main-build. We suspect it may be due to trying to compile non-existent directories during compilation. 
Removed Enablement E2E test directories from settings.gradle.kts which was removed in this [PR](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/770)
Also removed the dry run validator step in PR build

Update settings.gradle.kts to remove outdate code

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java

N/A
If we detect the span is a [Database span](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md) (by the existence of the `db.system`, `db.operation`, or `db.statement` attributes, except in the case of a [AWS SDK span](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/cloud-providers/aws-sdk.md), like DynamoDB SDK calls), we will provide a `RemoteResourceType` and `RemoteResourceIdentifier` as follows:
1. If an address attribute is present, and if a port attribute and/or db.name attribute is optionally present
1. RemoteResourceType = DB::Connection
2. RemoteResourceIdentifier = [db.name|]? {**address**} [|{**port**}]?
1. If any attribute contains | or ^ , they will be …

Add support on Database RemoteResourceType and RemoteResourceIdentifier

---

.github/workflows/appsignals-e2e-ec2-test.yml
.github/workflows/appsignals-e2e-eks-test.yml

Updating Enablement release testing to match this [PR](https://github.com/aws-observability/aws-application-signals-test-framework/commit/5e801e1a7a33e822270681d16e0d9c2cc02fcf6d).
Also updated the adot-pending-release branch with the latest changes.
[Test run](https://github.com/aws-observability/aws-application-signals-test-framework/actions/runs/9125340677) was done on the framework repo with the same workflow file as the Enablement release testing in OTEL Java. 

Update Release Testing with latest changes

---

.gitignore
appsignals-tests/contract-tests/build.gradle.kts
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcH2Test.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcPostgresTest.java
appsignals-tests/images/jdbc/build.gradle.kts
appsignals-tests/images/jdbc/src/main/java/software/amazon/opentelemetry/AppController.java
appsignals-tests/images/jdbc/src/main/resources/application.properties

N/A
Adding PostgreSQL contract tests for app signals to ensure that customer experience doesn't break with any change.
The new contract test follows the same structure as the current [JDBC test](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JDBC.java#L36) and asserts on the same fields of the spans and attributes.
To reuse the [same app](https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/appsignals-tests/images/jdbc/src/main) as the current test, added the following environment variables which are changed by each test:
- DB_URL
- DB_DRIVER
- DB_USERNAME
- DB_PASSWORD
- DB_PLATFORM
This …

Add app signals contract test for postgres

---

appsignals-tests/contract-tests/build.gradle.kts
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcH2Test.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcMySQLTest.java
appsignals-tests/images/jdbc/build.gradle.kts
appsignals-tests/images/jdbc/src/main/java/software/amazon/opentelemetry/AppController.java

NA
Adding MySQL contract tests for Application Signals to ensure customer experience won't break by any change.
As agreed in PR https://github.com/aws-observability/aws-otel-java-instrumentation/pull/806, we are refactoring JDBC related contracts to move them into a common base class. So adding a new JDBC related test like MySQL one is easy now.
This change also updated the create table sql statement as the existed one is invalid for MySQL.
---
```
➜  aws-otel-java-instrumentation git:(main) ./gradlew spotlessCheck
> Configure project :awsagentprovider
Inferred project: aws-otel-java-instrumentation, version: 1.33.0-SNAPSHOT …
```

Adding Application Signals Contract Test for MySQL

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcH2Test.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcMySQLTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcPostgresTest.java

Update the contract test to cover the new DB resource attributes `AWS_REMOTE_RESOURCE_TYPE` and `AWS_REMOTE_RESOURCE_IDENTIFIER` for JDBC calls
* For Mem DB, the new DB resource attributes are not expected to be generated
* For MySql and Postgresql, the expected format of 
* AWS_REMOTE_RESOURCE_TYPE = "DB:Connectoin"
* AWS_REMOTE_RESOURCE_IDENTIFIER = "db_name|db_server|db_port"

Contract test the new DB resource type and identifier attributes

---

buildSrc/build.gradle.kts
settings.gradle.kts

PR workflows are failing due to a somewhat arcane message relating to Docker and jib: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/9568113061/job/26377760995?pr=818
Found an issue that seems at least somewhat related, which was resolved in jib 3.4.1: https://github.com/GoogleContainerTools/jib/issues/4171
In this PR we are upgrading jib from 3.4.0 to 3.4.3, since a) it is generally a good thing to be up to date with dependencies and b) I suspect it will resolve this issue.

Upgrade jib

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/AppSignalsConstants.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java

- Added data base user attribute in EMF logs - `db.user`.
- Added unit test for data base user attribute
- Added contract-tests
Output of EMF log:
```
{
"Environment": "ECS",
... ,
"aws.remote.db.user": "myuser", <- Added Data base user
"Error": {
"Values": [
0
],
"Counts": [
75574
]
}
...
}
```
```
> Task :appsignals-tests:images:jdbc:jibDockerBuild                                                                                                                                            
Containerizing application to Docker daemon as aws-appsignals-tests-jdbc-app...                                                                                                                
Base image …
```

Adding data base user attribute in EMF logs

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java

The PR add new `RemoteResourceType` and `RemoteResourceIdentifier` for AWS Bedrock and BedrockRuntime services:
```
"RemoteResourceType": "AWS::Bedrock::Agent"
"RemoteResourceIdentifier": "<agent_id>"
"RemoteResourceType": "AWS::Bedrock::DataSource"
"RemoteResourceIdentifier": "<datasource_id>"
"RemoteResourceType": "AWS::Bedrock::Guardrail"
"RemoteResourceIdentifier": "<guardrail_id>"
"RemoteResourceType": "AWS::Bedrock::KnowledgeBase"
"RemoteResourceIdentifier": "<knowledgeBase_id>"
"RemoteResourceType": "AWS::Bedrock::Model"
"RemoteResourceIdentifier": "<modelId>"
``` 
Testing: E2E test performed to confirm trace, metrics are generated:
Traces:
AWS Java SDK V1:
AWS Java SDK V2:
Metrics:
AWS Java SDK V1:
AWS Java SDK V2:
By submitting this pull request, I confirm that my contribution is …

Add bedrock and bedrockRuntime support.

---

.github/workflows/e2e-tests-with-operator.yml

In this PR, we are changing E2E Operator tests to clean up after themselves on failure or cancellation. Currently, this only happens on cancellation, but we need to do this on failure too, as tests can fail due to leaked resources.
This operation is safe to perform, as E2E Operator tests are only run from [two locations](https://github.com/search?q=repo%3Aaws-observability%2Faws-otel-java-instrumentation%20e2e-tests-with-operator.yml&type=code):
1. [main-build](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/90901b191b0f9e934a4c698ec1d1448364ad86fd/.github/workflows/main-build.yml#L160-L162)
2. [nightly-upstream-snapshot-build](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/90901b191b0f9e934a4c698ec1d1448364ad86fd/.github/workflows/nightly-u …

Clean up E2E Operator resources if tests fail or are cancelled

---

tools/cp-utility/src/main.rs

This PR adds support for cp -r  command to copy recursively, and recursive copy will handle symbolic links as a normal test file.
Unit tests added.
and tested using the local built binary
`./target/debug/cp-utility -r README.md Find.md  `

Support to add `-r` to cp-utility tool

---

CONTRIBUTING.md
appsignals-tests/README.md
scripts/local_patch.sh

Starting from `release/v1.32.x`, we add patching scripts into main branch: https://github.com/aws-observability/aws-otel-java-instrumentation/pull/839
This PR add `local_patch.sh` script, which can be used to apply patch locally. Also update readme files to include local patching process. 
Testing:
This PR was tested with the following steps:
1. Merge in the code change from patching files from https://github.com/aws-observability/aws-otel-java-instrumentation/pull/839, `git merge release/v1.32.x`
2. Add contract tests to check span attributes added in patch file for:
```
AWS::Bedrock::KnowledgeBase
AWS::Bedrock::DataSource 
AWS::Bedrock::Agent 
```
Note: The contract test code change will be submitted in a follow-up PR.
3. confirm the span attributes are generated and contract test …

Add local patch script.

---

.github/workflows/release-build.yml

The 1.32.3 release failed to publish non-K8s/EKS related artifacts. As such, we will temporarily comment these out while working to resolve the authentication issues for the Maven artifacts that are not being published. In this way, we will only perform the failed steps and their prerequisite steps on the next attempt, so as to not change the image digest of the ECRs that have already been published.
Changing a github workflow file will NOT impact the released artifacts.

temp: Comment out ECR-related release steps

---

.github/workflows/e2e-tests-app-with-java-agent.yml
.github/workflows/e2e-tests-with-operator.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/owasp.yml

We want to report to us-east-1, as we do in Python https://github.com/aws-observability/aws-otel-python-instrumentation/blob/main/.github/workflows/daily_scan.yml#L16

Align metrics with other Repos

---

.github/workflows/nightly-upstream-snapshot-build.yml

Pointing to old workflow. Updated to align with main_build: https://github.com/aws-observability/aws-otel-java-instrumentation/blob/6158a3bf83538a448ea7e3da45faba751aee3c03/.github/workflows/main-build.yml#L226-L231
Sample failure: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/10553009806

Fix nightly-upstream-snapshot-build.yml

---

.github/workflows/publish-status.yml

Emit failure metrics instead of success metrics for easier monitoring.

Align failure metrics with other repos

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/jdbc/JdbcMySQLTest.java
appsignals-tests/images/jdbc/build.gradle.kts

Assert extra spans for MySQlConnectorJ-8.4.
When making a database query, Pulse agent leverage OTEL agent to intercept the database queries and send them to Cloud-watch agent. Then CloudWatch agent send all telemetry into Cloud-watch
We noticed that there will be two separate EMF log entries, one without remote identifier and one with remote identifier, this extra EMF comes in due to extra telemetry traces that come with mysqlConnector version 8.4
> The feature is supported by [component_telemetry](https://dev.mysql.com/doc/refman/8.4/en/telemetry-trace-install.html). MySQL Connector/J 8.4.0 introduces the client-side counterpart feature, with the capability of propagating the context to the MySQL Server it connects to and allowing a more complete observability …

Assert extra spans for MySQlConnectorJ-8.4.

---

.github/workflows/application-signals-e2e-test.yml
.github/workflows/main-build.yml
Dockerfile

This PR do the following two things:
1. Fix [recent main build failure](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/10926150649/job/30330248240) by updating Dockerfile syntax.
2. Add ECS E2E test entry point into main build.
An example of succeed test workflow: 
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/10926900740
(E2E operator test failure is expected, will plan on the effort fixing it).

Add ECS E2E test into main build

---

.github/workflows/application-signals-e2e-test.yml

We currently do not have full test coverage over our ADOT artifacts. We need to ensure that ADOT is compatible with Java versions, CPU architecture and different platforms before we release them. 
- Adding language version tests for Java 8, 17, 21, 22
- Adding CPU architecture test for ARM64
Java 8 currently does not work because the /mysql test case has a bug. Will follow up on fixing it in another PR
Test run: 
Test run for EKS: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/11149306942
Test run for rest: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/11148995161
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Add Application Signals E2E Test Coverage

---

instrumentation/jmx-metrics/src/main/resources/jmx/rules/jvm.yaml

Remove JVM metrics that are only used by Application Signals runtime to unblock CW JMX release.

Remove JVM metrics for CW JMX release

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java

- Updating the CFN Primary Id for Guardrail to be the ARN.  (Verified this in the AWS Cloudformation Console)
- Updated `BEDROCKAGENTOPERATION` enum.
- Our Bedrock Agent Runtime should support both Agent Operation and KnowledgeBased Operation [like in Java SDK v1](https://github.com/mxiamxia/opentelemetry-java-instrumentation/blob/965f7878c79c2be5851f23cf272edd39585f42af/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/AwsSdkExperimentalAttributesExtractor.java#L133).
Related changes in upstream package: https://github.com/mxiamxia/opentelemetry-java-instrumentation/pull/13
Set up sample apps and manually verified correct span attributes were generated via auto-instrumentation. 
`Java SDK v1`
`Java SDK v2`
By submitting this pull …

feat: update bedrock guardrail cfn primary id

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java

Remove `RemoteResourceTargetIdentifier` attribute which will treat Lambda Function as a regular AWS resource. It may conflict with the current concept that have Lambda function defined as a service.

Remove Lambda:Function:Name resource type support 

---

Dockerfile

Update Dockerfile to use public ECR image
Update Dockerfile to use public ECR image

Update Dockerfile to use public ECR image

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/base/ContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/RuntimeMetricsTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/AppSignalsConstants.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/MockCollectorClient.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java
instrumentation/jmx-metrics/src/main/resources/jmx/rules/jvm.yaml

Add runtime metrics collection into Application Signals.
This PR is an umbrella PR to track the ongoing changes for runtime metrics.
1. [Add Application Signals runtime metrics with feature disabled #900](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/900) [Merged in main]
2. [feat: Add contract tests for runtime metrics #893](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/893)
3. Enable runtime metrics by default

Add Application Signals runtime metrics

---

.github/workflows/main-build.yml

E2E Operator test is currently failing due to a known issue. We do not have an immediate plan to fix it so commenting it out for now. 
Example failed run: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/11525535146/job/32241628521

Comment out E2E Operator Test

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java

Main-build Enablement E2E tests started failing starting from this [PR](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/899). It was due to the usage of `isEmpty()` for Optional datatypes, which is available only from Java 11
Change .isEmpty() to .isPresent() for optional types

Switch isEmpty() to .isPresent() for Optionals Type

---

.github/workflows/main-build.yml
.github/workflows/owasp.yml
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/base/ContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/RuntimeMetricsTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/AppSignalsConstants.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/MockCollectorClient.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
instrumentation/jmx-metrics/src/main/resources/jmx/rules/jvm.yaml
scripts/docker/corretto-slim/Dockerfile

1. [Switch isEmpty() to .isPresent() for Optionals Type #939](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/939)
1. [Comment out E2E Operator Test #940](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/940)
1. [Add Application Signals runtime metrics #892](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/892)
1. [Update Dockerfile for corretto-slim build #924](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/924)

Release v1.32.5

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/base/ContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/base/JMXMetricsContractTestBase.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/jmx/JVMMetricsTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/jmx/KafkaBrokerMetricsTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/jmx/KafkaConsumerMetricsTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/jmx/KafkaProducerMetricsTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/jmx/TomcatMetricsTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/JMXMetricsConstants.java
appsignals-tests/images/kafka/kafka-consumers/src/main/java/App.java
appsignals-tests/images/kafka/kafka-producers/src/main/java/com/amazon/sampleapp/App.java
appsignals-tests/images/mock-collector/src/main/java/software/amazon/opentelemetry/appsignals/test/images/mockcollector/Main.java
appsignals-tests/images/mock-collector/src/main/java/software/amazon/opentelemetry/appsignals/test/images/mockcollector/MockCollectorMetricsService.java

*Description of changes:* Adds contract tests to verify the expected behavior of the following changes:
- https://github.com/aws-observability/aws-otel-java-instrumentation/pull/817
- https://github.com/aws-observability/aws-otel-java-instrumentation/pull/898
- https://github.com/aws-observability/aws-otel-java-instrumentation/pull/901
Starts up sample apps with the instrumented SDK and verifies that metrics are received for each of the supported JMX target systems.

Add JMX contract tests

---

README.md

update resource link in README.md since it has moved to [opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib) repository

Fix link to AWS Resources in README.md

---

awsagentprovider/build.gradle.kts
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/OtlpUdpSpanExporter.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/OtlpUdpSpanExporterBuilder.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/UdpSender.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/UdpExporterTest.java

Adding a new `SpanExporter` that can export spans to a configurable endpoint over UDP.
- The spans are first protobuf encoded, then base64 encoded, then prefixed with `T1S` or `T1U` (depending on sampled), and finally appended to the `{"format":"json","version":1}\n` string before being exported to the endpoint, default is `127.0.0.1:2000`.
- Related: https://github.com/aws-observability/aws-otel-python-instrumentation/pull/232
Wrote a test to create and export a real span via X-Ray Daemon running locally.
- Unit test
```java
@Test
public void testExporter() { // TODO: only for testing. remove.
Tracer tracer = OpenTelemetrySdk.builder().build().getTracer("hello");
Span mySpan = tracer.spanBuilder("DoTheLoop_5").startSpan();
int numIterations = 5;
mySpan.setAttribute("NumIterations", …
```

Adding UdpExporter for Otlp spans

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsUnsampledOnlySpanProcessor.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsUnsampledOnlySpanProcessorBuilder.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsUnsampledOnlySpanProcessorTest.java

Following the approach as ADOT Python: https://github.com/aws-observability/aws-otel-python-instrumentation/pull/247. Note that the span attribute key was [later changed to `aws.trace.flag.sampled`](https://github.com/aws-observability/aws-otel-python-instrumentation/pull/260).
Introducing `AwsUnsampledOnlySpanProcessor` that can be appended to a `TracerProvider`. This span processor wraps a `BatchSpanProcessor` for delegating all the operations after processing. The `AwsUnsampledOnlySpanProcessor` does 2 things:
- onStart - Sets the `aws.trace.flag.sampled` span attribute on each span.
- onEnd - If the span is unsampled, only then it is delegated to the BSP, otherwise it is dropped.
```
@Test
public void testExportingUnsampledSpan() {
SpanProcessor unsampledSpanProcessor = …
```

Adding AwsUnsampledOnlySpanProcessor to export batches of unsampled spans

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsUnsampledOnlySpanProcessor.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsUnsampledOnlySpanProcessorBuilder.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsUnsampledOnlySpanProcessorTest.java

The following behaviors are implemented when the ADOT Java SDK is running in a Lambda environment:
- Replace the OTLP SpanExporters (either HTTP or GRPC ones) with `OtlpUdpSpanExporter` to export spans to Lambda agent over UDP.
- Disable the other AWS resource providers via [the `otel.java.disabled.resource.providers` configuration](https://opentelemetry.io/docs/languages/java/configuration/#properties-general).
- Set [the BSP configuration](https://opentelemetry.io/docs/languages/java/configuration/#properties-traces) `otel.bsp.max.export.batch.size` to 10 for the auto-configured BatchSpanProcessor that exports the sampled spans.
- When Application Signals is enabled:
- Export unsampled spans too via the `AwsUnsampledOnlySpanProcessor`. Also, setting the batch size for the …

Configure SDK when running in Lambda environment

---

lambda-layer/build-layer.sh
lambda-layer/otel-instrument

As a follow up to the https://github.com/aws-observability/aws-otel-java-instrumentation/pull/953 and from internal discussion with @wangzlei:
- Renaming `otel-handler` to `otel-instrument` to be consistent with other ADOT lambda layer script naming.
- Enabling Application Signals by default with the following environment variables already set. Note that users can still override these environment variables if they want to.
```
AWS_LAMBDA_EXEC_WRAPPER=/opt/otel-handler
OTEL_AWS_APPLICATION_SIGNALS_ENABLED=true
OTEL_LOGS_EXPORTER=none
OTEL_METRICS_EXPORTER=none
OTEL_TRACES_EXPORTER=otlp
```
- Appending Lambda resource attributes
ADOT Python implementation for reference: https://github.com/aws-observability/aws-otel-python-instrumentation/blame/main/lambda-layer/src/otel-instrument
By …

Renaming to otel-instrument and default configs

---

.github/patches/opentelemetry-java-instrumentation.patch
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/v1/AwsSdkV1Test.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/v2/AwsSdkV2Test.java

Revert the following two PRs to avoid using `jackson-databind` as dependency:
1. Set Up LLM Inference Attributes Auto-Instrumentation Java v1: https://github.com/mxiamxia/opentelemetry-java-instrumentation/pull/21
2. Set Up LLM Inference Attributes Auto-Instrumentation Java v2: https://github.com/mxiamxia/opentelemetry-java-instrumentation/pull/22

Revert bedrock runtime change.

---

.github/collector/collector-config.yml
.github/workflows/e2e-tests-app-with-java-agent.yml
scripts/docker/corretto-slim/Dockerfile

Change back to use java 17 base image.
The previous [ADOT Java main build failed](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/12421612708/job/34682282673) because of it is using the collector version v0.42.0 released 8 hours ago, where the logging exporter has been deprecated. This PR migrate to debug exporter according to:
https://github.com/open-telemetry/opentelemetry-collector/issues/11337.

Migrate logging to debug exporter to match with latest otel colletor.

---

.github/collector/docker-compose.yml

Add `OTEL_EXPORTER_OTLP_PROTOCOL` to `grpc` for instrumentation as in [version v2.0.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0):
> The default OTLP protocol has been changed from grpc to http/protobuf in orderto align with the specification.

Use grpc exporter for agent test workflow.

---

.github/collector/docker-compose.yml

Previously, in v1.x, the springboot controller telemetry data is enabled by default.
Starting from upstream v2.x, the controller telemetry need to be enable by setting up env `OTEL_INSTRUMENTATION_COMMON_EXPERIMENTAL_CONTROLLER_TELEMETRY_ENABLED`: https://opentelemetry.io/docs/zero-code/java/agent/disable/#suppressing-controller-andor-view-spans. 
This PR enable the telemetry data to align with smoke test validator.
https://opentelemetry.io/docs/zero-code/java/agent/disable/#suppressing-controller-andor-view-spans

Enable smoke test controller telemetry.

---

lambda-layer/.gitignore
lambda-layer/build-layer.sh
lambda-layer/build.gradle.kts
lambda-layer/otel-instrument
lambda-layer/patches/aws-otel-java-instrumentation.patch
lambda-layer/patches/opentelemetry-java-instrumentation.patch

- Fast Startup feature was added as opt-in in the upstream some time ago: https://github.com/open-telemetry/opentelemetry-lambda/pull/1180 (includes perf improvement results)
- Did some of my own testing on a Java17 Lambda function with 3GB of memory and noticed cold start time improvement from 8.7 seconds to 4.2 seconds.
- Since the ADOT 1.x version has been updated to lated 1.33.6 version of upstream, we need to update the lambda layer related patches to this version as well. 
- Tested by manually building the layer and instrumenting a sample lambda function. 

Updating Lambda Patch v1.33.6 + Fast Startup capability

---

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/base/AwsSdkBaseTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/SemanticConventionsConstants.java

Same as https://github.com/aws-observability/aws-otel-java-instrumentation/pull/976 but merging to our v1.33.x patch branch
*Test plan:*
Ran updated contract tests.

Update gen ai contract tests in v1.33.x patch branch

---

.github/patches/opentelemetry-java-instrumentation.patch
licenses/licenses.md

Update dependencies and Otel to v1.33.0 for ADOT release.
dependency reports:
```./gradlew dependencyUpdates
> Configure project :awsagentprovider
Inferred project: aws-otel-java-instrumentation, version: 1.33.0-SNAPSHOT
> Task :dependencyManagement:dependencyUpdates
------------------------------------------------------------
:dependencyManagement Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest release version:
- com.sparkjava:spark-core:2.9.4
- com.squareup.okhttp3:okhttp:4.12.0
- io.opentelemetry:opentelemetry-extension-aws:1.20.1
The following dependencies have later release versions:
- com.amazonaws:aws-java-sdk-bom …
```

Update dependencies and Otel to v1.33.0

---

.github/workflows/application-signals-e2e-test.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/owasp.yml

1. Updating image scan workflow to v1.32.6 as part of MCM release for new
version.
2. update actions/upload-artifact and actions/download-artifact to v4 as v3 is marking as deprecated: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update image scan workflow to v1.33.0.

---

sample-apps/apigateway-lambda/settings.gradle.kts
settings.gradle.kts

The sample app doesn't need ADOT Javaagent instrumentation, rather it depends on instrumentaiton via lambda layer. SO it makes sense to not depend on adot javaagent build for building this sample app.

decouple apigw-lambda sample app from adot project build

---

lambda-layer/build-layer.sh

The current logic is including the full path of the `aws-opentelemetry-javaagent.jar` in the zip. But it should be at the root along-with the `otel-instrument` file.
Tested locally and verified the directory structure is now correct.

fix packaging of the layer artifacts

---

.github/workflows/release-lambda.yml

Adding a manually triggered workflow to release the java lambda layers to multiple regions.
Tested by running the workflow in my fork, and confirmed that the layer was successfully published in `us-east-1`.
GH run: https://github.com/srprash/aws-otel-java-instrumentation/actions/runs/12738121465

add lambda release workflow - main branch

---

.github/workflows/release-lambda.yml

Same as https://github.com/aws-observability/aws-otel-java-instrumentation/pull/994 but for the 1.33.x branch where we will be doing the release for ADOT v1 lambda layer from.

add lambda release workflow - v1.33.x branch

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java
lambda-layer/patches/opentelemetry-java-instrumentation.patch

The instrumentation produces 2 lambda root spans upon each invocation of the function. This is a known issue in OTel: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7808
- Otel has fixed it in [this PR](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10736) but the change wasn't ported to the 1.x versions. So I took the diff from the upstream commit and made it into a patch that we apply when building the ADOT Java Lambda Layer for v1.33.x.
On lambda environment, we export 100% of the spans to X-Ray to ensure we are able to provide 100% Application Signals metrics. However, currently only the sampled spans show up on the "Services" page and the unsampled spans do not.
- Upon comparing the sampled vs unsampled spans, I noticed that the …

[Bug fixes] Lambda - duplicate lambda spans + appsignals from unsampled spans

---

sample-apps/apigateway-lambda/build.gradle.kts
sample-apps/apigateway-lambda/src/main/java/com/amazon/sampleapp/LambdaHandler.java
sample-apps/apigateway-lambda/terraform/main.tf

Related to https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1002, we want to use native Java Http Client instead of OkHttp in the sample app.
Also, I noticed that the other language sample apps ([Python](https://github.com/aws-observability/aws-otel-python-instrumentation/blob/main/lambda-layer/sample-apps/function/lambda_function.py#L15)) does a `ListBuckets` call whereas this sample app is doing `ListBucket` call. So updating that to be consistent with others.

Update Lambda sample app - switch to native http client +switch to ListBuckets API call

---

.github/workflows/application-signals-e2e-test.yml

The current nstrumentation was lacking ubuntu test
Added the ubuntu test to the instrumentation
This is the workflow link:  https://github.com/Jeel-mehta/aws-application-signals-test-framework/actions/runs/13001021774

[Java] Add ubuntu test

---

lambda-layer/patches/opentelemetry-java-instrumentation.patch

In the [previous bugfix](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1000), we missed porting this change from OTel specifically for Java 8 and 11 runtimes. 
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10942
**Testing:** Created an ADOT lambda layer with the change and verified that the duplicate lambda spans do not appear for Java 11, 17, and 21.

[Bugfix] Duplicate lambda spans in Java 11

---

.github/workflows/application-signals-e2e-test.yml
.github/workflows/main-build.yml
.github/workflows/nightly-upstream-snapshot-build.yml
.github/workflows/release-lambda.yml

The `upload-artifacts` and the `download-artifacts` v3 are deprecated and causing the workflows to be stopped. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

bump up the upload-download artifact action to v4

---

.github/workflows/main-build.yml
.github/workflows/release-lambda.yml

Same as https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1012 but for the release 1.33.x branch.

bump up the upload/download artifact action to v4

---

.github/workflows/release-lambda.yml

*Issue*: The `upload-artifact@v4` action no longer allows uploading artifacts with same name. Thus the release lambda workflow fails: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/13146172757
- Taking the [fix that was done for the Application Signals .Net Lambda Layer](https://github.com/aws-observability/aws-otel-dotnet-instrumentation/commit/d75276960b465ae22af23282ed34eaf90cf5779b):
- Appending region to the artifact name for making it unique
- While downloading these artifacts we will just merge.

Unique artifact names for upload and merge for download

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java

**Issue #, if available:**
Lambda Topology issue -- more context in PRs for Python and JavaScript:
- https://github.com/aws-observability/aws-otel-python-instrumentation/pull/319
- https://github.com/aws-observability/aws-otel-js-instrumentation/pull/149
- Apply fix for the Lambda Topology issue. The logic mimics the fix in our other ADOT SDKs.
- Adding back AWS Resource support for Lambda.
- https://github.com/aws-observability/aws-otel-java-instrumentation/pull/907
- We previously removed support due to the Lambda Topology issue
**Test plan:**
Set up two Lambda functions with Java runtimes and tested with custom Lambda layer with fix built-in. Tested both AWS SDK v1 and v2. Below are screenshots of the topology for various configurations.
**v1 Topology …

Fix: Lambda Topology Issue

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanMetricsProcessor.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanMetricsProcessorTest.java

ADOT SDK resource detectors by default have enabled a few AWS resource detector which will call EC2 metadata API endpoints. These activities have been captured by auto-instrumentation and generated AppSignals metrics.
These calls should be present in traces, but not in metrics. 
Suppress AwsSpanMetricsProcessor from generating metrics when the RemoteService points to `169.254.169.254`
*Testing*
Deployed two EC2 instance with Java sample application and ADOT Java 
- `sample-application-2025-02-06-test`: ADOT Java with changes in this PR
- `sample-application-2025-02-06`: Public latest ADOT Java
*Traces:*
Present from both EC2 instance
*Metrics*:
Present only for `sample-application-2025-02-06`:
*Logs*:
Present only for …

Remove spans with ec2 metadata ip address from metrics

---

.github/workflows/owasp.yml

The download url for the dependency check release changed, causing the daily scan alarm to fail

Fix dependency scan in daily scan alarm

---

lambda-layer/build-layer.sh
lambda-layer/patches/StreamHandlerInstrumentation.patch

Problem:
All Lambda Java users using HandleStreamRequest experience broken application signal traces. This issue affects all Spring Boot 3 users.
Cause:
AWS Lambda for Java provides two handler interfaces: com.amazonaws.services.lambda.runtime.RequestHandler com.amazonaws.services.lambda.runtime.RequestStreamHandler However, instrumentation for RequestStreamHandler is missing in the OpenTelemetry Java agent.
Fix:
Added instrumentation support for RequestStreamHandler.
Test:
Unit tests pass (./gradlew spotlessCheck assemble instrumentation:test). Manual end-to-end tests pass:
Deployed Lambda functions with Spring Boot 3 and Amazon Serverless Java Container. Enabled application signals, observed broken traces. Disabled application signals and added a private build of the Java layer for …

feat: Add instrumentation for Lambda Java interface HandleStreamRequest

---

otelagent/build.gradle.kts

HTTP metric is disabled with the following error message.
`
[otel.javaagent 2025-03-04 19:21:31:397 +0000] [http-nio-8080-exec-1] WARN io.opentelemetry.javaagent.shaded.instrumentation.api.internal.OperationMetricsUtil - Disabling http server metrics because io.opentelemetry.sdk.metrics.SdkDoubleHistogram$SdkDoubleHistogramBuilder does not implement io.opentelemetry.javaagent.shaded.io.opentelemetry.api.incubator.metrics.ExtendedDoubleHistogramBuilder. This prevents using metrics advice, which could result in http server metrics having high cardinality attributes.
`
From the dependency tree, it is introduced by `io.opentelemetry:opentelemetry-exporter-otlp`.
```
|    +--- io.opentelemetry:opentelemetry-exporter-otlp -> 1.44.1
|    |    +--- …
```

Exclude opentelemetry-extension-incubator

---

.github/workflows/owasp.yml

This PR adds both v1 and v2 in the daily image scan.
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/13661325124/job/38192925936

Add v1 and v2 to daily image scan

---

lambda-layer/patches/StreamHandlerInstrumentation.patch

- **V2 Issue:** [Non-top-level server span created by Lambda instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7808)  
- **V2 PR:** [#10736](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10736)  
The fix has been ported to v1 as a patch for non-stream handlers. This change extends the fix to the stream handler in the v1 repository.  
- All unit tests pass.  
- End-to-end tests pass.  (with Java11, 17, and 21 runtime on Lambda)
- No risk of breaking existing functionality.  
- The change only adds instrumentation for `RequestStreamHandler` without modifying existing behavior for `RequestHandler`.  
- Existing users who do not use `RequestStreamHandler` remain unaffected.  
By submitting this pull request, I confirm that …

Port upstream fix (PR#10736) to downstream v1 Lambda stream handler

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsLambdaSpanProcessor.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsLambdaSpanProcessorTest.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtilTest.java

When a microservice is hosted in a Lambda Java environment (e.g., a Spring Boot app), this PR ensures the following to provide a better observation experience:
The microservice will emit a server span that follows Lambda's server span. 
Lambda's server span will be tagged with aws.trace.lambda.multiple-server=true.
If Lambda detects the HTTP call context, the operation attribute will be set as the HTTP method and path, instead of FunctionHandler.
Test:
All unit tests pass.
Built the Java layer and Spring Boot app on Lambda, and completed end-to-end testing.

feat: Support microservice span in Lambda Java environment.

---

.github/workflows/owasp.yml

add retry step for `Install and run dependency scan` which has higher transient failure rate.
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/13637396412/job/38119414216

Add retry for the unstable steps in daily_scan workflow

---

.github/workflows/application-signals-e2e-test.yml

Follow up to: https://github.com/aws-observability/aws-application-signals-test-framework/pull/381

Add SigV4 release test to main build 

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java

AWS Resource Detectors are currently only enabled when Application Signals are enabled. This behavior is different than other languages which enables the detectors regardless of AppSignals.
Modified the logic in auto instrumentation Java Agent to enable resource detection (except for Lambda) without AppSignals.
*Test*
Ran a sample app on EC2 instance with ADOT Java Agent with the following environment variables:
```
export OTEL_AWS_APPLICATION_SIGNALS_ENABLED=false
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://xray.us-east-1.amazonaws.com/v1/traces
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
export OTEL_LOGS_EXPORTER=console
export OTEL_LOGS_EXPORTER_ENDPOINT=none
export OTEL_METRICS_EXPORTER=none
export …
```

Enable AWS Resource Detectors without AppSignals

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java

We do not want to automatically disable Application Signals if SigV4 is enabled. This PR allows Application Signals to run normally with SigV4.

Decouple SigV4 from Application Signals

---

Dockerfile

Release build failed with:
Updating rust version required for `edition2024` 

Update rust version

---

.github/workflows/release-build.yml
.github/workflows/release-lambda.yml
.github/workflows/release-udp-exporter.yml

**Issue:**
Any branch can run critical release workflows without obtaining proper approval.
- Leveraging [GitHub Environment](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-environments-for-deployment) to enforce safety of release workflows.
- The releases should now require approval from the "aws-observability/aws-application-signals-team" member to run.
**Testing**:
Tested in this branch itself. The workflow blocks on approval. Screenshot below.

Release safety

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtilTest.java

Currently the local operation of lambda span is hardcoded to function_name//FunctionHandler. In some use cases, some server is running inside lambda function and we should allow the setting of the local operation dynamically at run time. For example, users can use span api to set the attribute `aws.lambda.local.operation.override` and then this value can be used for the local operation. We have an Amazon-internal framework instrumentation that depends on this.

update local operation of lambda span based on span attribute

---

.github/patches/opentelemetry-java-instrumentation.patch
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/base/AwsSdkBaseTest.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/v1/AwsSdkV1Test.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/awssdk/v2/AwsSdkV2Test.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/AppSignalsConstants.java
appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/SemanticConventionsConstants.java
appsignals-tests/images/aws-sdk/aws-sdk-v1/src/main/java/com/amazon/sampleapp/App.java
appsignals-tests/images/aws-sdk/aws-sdk-v2/src/main/java/com/amazon/sampleapp/App.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/SqsUrlParser.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/SqsUrlParserTest.java

Changes in ADOT package to support cross-account observability in Java V1 & V2 SDK.
1. We extract account id and region from remote resource arn. 
2. We pass account access key id and region from span to metric when resource arn is not available. 
3. Add instrumentation patch for AWS SDK
Related changes in upstream package: https://github.com/yiyuan-he/opentelemetry-java-instrumentation/pull/2
**Testing Plan:**
1. Unit tests for extracting account id and region from remote resource arn.
2. Unit tests for extracting access key and region from credential.
3. Unit test for the scenario when resource arn and credential information are both available.
5. Contract tests
By submitting this pull request, I confirm that my contribution is made under the terms of the …

feat: Extract account/access key id and region for cross-account support

---

instrumentation/aws-sdk/README.md
instrumentation/aws-sdk/build.gradle.kts
instrumentation/aws-sdk/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/awssdk_v1_11/AdotAwsSdkClientInstrumentation.java
instrumentation/aws-sdk/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/awssdk_v1_11/AdotAwsSdkInstrumentationModule.java
instrumentation/aws-sdk/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/awssdk_v1_11/AdotAwsSdkTracingRequestHandler.java
instrumentation/aws-sdk/src/main/resources/META-INF/services/io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule
instrumentation/aws-sdk/src/test/java/software/amazon/opentelemetry/javaagent/instrumentation/awssdk_v1_11/AdotAwsSdkClientAdviceTest.java

This PR is similar to #1111, as it sets a base SPI implementation for AWS SDK v1.11.
This is the skeleton set up for the SPI, which aims to remove the [patch](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/.github/patches/opentelemetry-java-instrumentation.patch) for aws-sdk v1.11 by using OTel's InstrumentationModule SPI extension. This instrumentation is essentially complementing the upstream java agent. It is completely separate from upstream and instruments after the Otel agent.
This PR sets up the foundational structure for AWS SDK v1.11 Instrumentation, moving away from the current patching approach. It doesn't modify current ADOT functionality or the upstream span. It just registers the ADOT SPI  implementation and sets up the interceptor hooks.
1. …

Base of AWS SDK v1.11 SPI Implementation

---

.github/workflows/e2e-tests-app-with-java-agent.yml
.github/workflows/main-build.yml

Emit a failure metric if main build fails. Since this workflow is triggered with pushes to main or a release branch, we want to be notified if there is a failure with the build process or e2e tests.
Tested by temporarily adding an on: push: trigger to my own branch in this repo and testing the updated workflow. Verified that failure metric was successfully published to cloudwatch.
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/16783145872

Send main build metrics

---

.github/workflows/main-build.yml
.github/workflows/release-lambda.yml
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsLambdaSpanProcessor.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsLambdaSpanProcessorTest.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtilTest.java
lambda-layer/.gitignore

This change merges all private Lambda Java updates from the v1.33 branch into the v2.11.x branch.  I performed a 'git rebase v2.11' on the v1.33 branch, reviewed all changes, and completed the build and testing process. The resulting Lambda layer generated trace data identical to the version built directly from the v2.11.x branch (excluding this PR).
Here is the list of all migrated PRs:
Build layer during CI/CD workflows + some minor refactoring #989 
support java11 runtime for lambda #1001 
Unique artifact names for upload and merge for download #1014 
Bug fixes] Lambda - duplicate lambda spans + appsignals from unsampled spans #1000 
Fix: Lambda Topology Issue (#1016)
Fix: Lambda Topology Issue (#1016) #1085
feat: Support microservice span in Lambda Java environment. #1053
Test
Tested …

[Lambda Java v2.11.x] Merge All Code Changes from v1.33.x Branch into v2.11.x

---

.github/workflows/main-build.yml

Removing problematic backslash which was making the workflow invalid: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/16840663861
Fixed in my branch release/v2.11.2 - https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/16841343395
Reciprocating the same change in main

Fix YAML syntax error in main-build workflow

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGenerator.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtil.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsMetricAttributeGeneratorTest.java
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsSpanProcessingUtilTest.java

This PR adds a utility method to help migrate deprecated semconv keys. It first checks the new key; if the new key is not available, it falls back to the legacy deprecated key.
This PR also handles the following deprecated keys:
MESSAGING_OPERATION
SERVER_SOCKET_ADDRESS
SERVER_SOCKET_PORT
Tests:
./gradlew build test — Pass
./gradlew appsignals-tests:contract-tests:contractTests — Pass 
Manual E2E with Spring Boot sample app: Compared raw span data with and without this change — Pass

[semconv]: Add functions to support migration of deprecated semconv keys

---

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AttributePropagatingSpanProcessor.java
awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAttributeKeys.java

Propagate the sampling decision as an attribute to allow anomalies captured through adaptive-sampling local SDK configuration to be identified in the console more easily. See #1141 
Also removed unused AwsAttributeKey
Deployed to test environment and all spans now have the flag appropriately set under both sampled and manually exported circumstances.

Propagate sampling decision as attribute

---

.github/patches/opentelemetry-java-contrib.patch

- Implemented a sampling rule-to-hash map and hash-to-rule map that are filled in on the initialization of the XrayRulesSampler object and on any updates from the scheduled GetSamplingRules calls
- Implemented logic to use the encoded values in the trace state (passed to AwsSamplingResult)
- Updated unit tests
Trace state addition from adaptive sampling should now be `xrsr=123abc12` instead of something like `awsxraysamplingrule=MyReallyLongSamplingRuleName`
Reason: Trace state header is a shared space between vendors providing tracing. OTel or other vendors may also be using the trace state for propagating information, so with a limited space of 256 characters it is our job to shorten our usage of the space as much as possible.
Changes deployed to test environment and tested against all …

Shorten trace state usage for adaptive sampling

---

.github/patches/opentelemetry-java-contrib.patch
awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProviderTest.java
awsagentprovider/src/test/resources/adaptive-sampling-config-invalid.yaml
awsagentprovider/src/test/resources/adaptive-sampling-config-valid.yaml

1. Customers should be able to see not only the span that is an anomaly from the error capture logic, but also the rest of the spans in that trace where possible
2. Statistics should be accurate even if a service is called multiple times as part of the same trace, i.e. the current segment/operation closing and returning is not enough to signal the end of the trace, we need to keep track of the trace ID and ensure any repeated calls to a service as part of the same trace are 
- Replace `anomalyTracesSet` with `traceUsageCache`: This cache represents the last operation that was done on a given trace within the last 10 minutes relating to adaptive sampling features. It is implemented using [Caffeine](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/2.9.3/index.html), a …

[Adaptive Sampling] Capture all spans in anomaly traces + more

---

.github/patches/opentelemetry-java-contrib.patch

Change was already previously present, but was removed mistakenly: https://github.com/aws-observability/aws-otel-java-instrumentation/blob/8c8b717bea21d4c0afc43c6c2803254e58c4512e/.github/patches/opentelemetry-java-contrib.patch
Reintroducing the fix in the patch

Fix disk-buffering build failure in contrib

---

dependencyManagement/build.gradle.kts

Fixes [CVE-2025-58056](https://github.com/advisories/GHSA-fghv-69vj-qj49). See upstream [PR](https://github.com/aws/aws-sdk-java-v2/pull/6398).

bump Netty to 4.1.126

---

sample-apps/udp-exporter-test-app/build.gradle.kts

- Fix failing workflow `udp-exporter-e2e-test`, where the sample app is unable to be built
- https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/17587060722/job/49957841960
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':compileKotlin'.
> Unknown Kotlin JVM target: 21
```
- Update Kotlin version in UDP Exporter Sample Test App. It is also now aligned with the Kotlin version used in other `build.gradle.kts` files in this repo.

Update Kotlin version in UDP Exporter Sample Test App

---

.github/patches/opentelemetry-java-contrib.patch

Changed logic for rule name trace state propagation to ensure in the case that services are in different AWS accounts the root service's applied rule name continues to propagate. This allows for the account to boost effectively if the original AWS account is reached again in a downstream service, e.g. Service A in Acct1 -> Service B in Acct2 -> Service C in Acct1.
Deployed to demo environment in which all services (A, B, C) are running in an EC2 instance. Created a new sampling rule and restarted services A and C. As the SDK calls GetSamplingRules every 5 minutes, in this 5 minute window service B did not send any statistics to the new sampling rule or to any other but service C was still able to send statistics for boost to service A.
By submitting this pull request, I confirm that my …

[Adaptive Sampling] Ensure sampling rule propagation across AWS accounts

---

.github/workflows/application-signals-e2e-test.yml

We depend on [OTEL Java 2.11.0](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/release/v2.11.x/dependencyManagement/build.gradle.kts#L30C20-L30C26), which was released [Dec 23, 2024](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.11.0), at which Java 23 was supported (released [2024-09-17 ](https://www.java.com/releases/)). We should have bumped this version then, but we didn't have a good process in place at the time. Bump version now.
Skipping changelog as there is no changelog in this branch.

 Update Java lang version support from 22 to 23

---

.github/workflows/application-signals-e2e-test.yml

We depend on [OTEL Java 2.11.0](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/release/v2.11.x/dependencyManagement/build.gradle.kts#L30C20-L30C26), which was released [Dec 23, 2024](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.11.0), at which Java 23 was supported (released [2024-09-17 ](https://www.java.com/releases/)). We should have bumped this version then, but we didn't have a good process in place at the time. Bump version now.
Skipping changelog as we will support Java 24 soon.

Update Java lang version support from 22 to 23

---

.github/actions/patch-dependencies/action.yml
.github/patches/opentelemetry-java-contrib.patch
.github/patches/opentelemetry-java-instrumentation.patch
.github/scripts/patch.sh
CHANGELOG.md
dependencyManagement/build.gradle.kts
lambda-layer/build-layer.sh
lambda-layer/patches/aws-otel-java-instrumentation.patch
lambda-layer/patches/opentelemetry-java-instrumentation.patch
scripts/local_patch.sh

Adaptive Sampling:
- https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1183
- https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1186
- https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1188
Other changes that were made to handle merge conflicts/build issues:
- Reimplemented the following contrib change to simply count/not count statistics based on whether the parentContext is valid (same logic as `ParentBasedSampler`) instead of wrapping the `XrayRulesSampler` with a `ParentBasedSampler`. This ensures the `XrayRulesSampler`'s adaptive sampling logic still takes effect in all cases. https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1488
- Fix a build issue in the contrib: …

Merge 2.11.5 back into main branch
