awsagentprovider/build.gradle.kts, awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAgentProperties.java, awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsOpenTelemetryFactory.java, awsagentprovider/src/main/resources/META-INF/services/io.opentelemetry.javaagent.shaded.io.opentelemetry.spi.OpenTelemetryFactory, awsagentprovider/src/main/resources/META-INF/services/io.opentelemetry.javaagent.spi.config.PropertySource, awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsOpenTelemetryFactoryTest.java, build.gradle.kts, otelagent/build.gradle.kts, otelagent/src/main/java/software/amazon/opentelemetry/javaagent/bootstrap/AwsAgentBootstrap.java
*Description of changes:* Prepare for Maven Central by moving namespace.
=> Move packages / artifacts to maven-usable namespaces.

sample-apps/spark/build.gradle.kts, sample-apps/springboot/build.gradle.kts
*Description of changes:* We definitely don't want to override version with a constant. And there's no reason to override group either.
=> Don't set version or group in sample apps.

.github/workflows/main-build.yml
*Description of changes:* Uses https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/validator/src/main/resources/validations/springboot-otel-trace-metric-validation.yml for validation (I think)
=> Use springboot validator instead of default

build.gradle.kts
=> Sign artifacts when publishing.

.github/workflows/main-build.yml, .github/workflows/release-build.yml
=> Pass GPG secrets to workflows.

.github/workflows/main-build.yml, .github/workflows/release-build.yml, build.gradle.kts
*Description of changes:* Sets up sonatype publishing target (confirmed can upload locally). Also moves integration test image publishing to after GitHub artifact publishing since they are less important (we wouldn't want to fail other steps if they happen to fail for some reason).
=> Set up sonatype publishing

build.gradle.kts, settings.gradle.kts
*Description of changes:* Apache HTTP client conflict when it's added
=> Remove staging plugin for now since causes dependency conflict with jib.

awsagentprovider/build.gradle.kts, awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsOpenTelemetryFactory.java, dependencyManagement/build.gradle.kts
*Description of changes:* This should fix integration tests too
=> Update to agent 0.12.0

build.gradle.kts
*Description of changes:* Missing a few fields that maven central will need
=> Fill up required POM fields.

.github/workflows/release-build.yml
Updated sample app ECR repository name in release workflow
=> Update sample app image name in release workflow

awsagentprovider/build.gradle.kts, awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsOpenTelemetryFactory.java, dependencyManagement/build.gradle.kts, otelagent/build.gradle.kts
=> Update agent dependency to 0.13.0

.github/workflows/docker-build-corretto-slim.yml, .github/workflows/docker-build-smoke-tests-fake-backend.yml, .github/workflows/main-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/release-build.yml, otelagent/build.gradle.kts, sample-apps/spark/build.gradle.kts, sample-apps/springboot/build.gradle.kts, smoke-tests/fakebackend/build.gradle.kts, smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/SpringBootSmokeTest.java, smoke-tests/spring-boot/build.gradle.kts
Was still using ghcr here, but let's finally switch to ecr. The URL doesn't have to look great for these testing images so it's just a default random alias name
=> Switch from ghcr to ecr

dependencyManagement/build.gradle.kts, sample-apps/spark/src/main/java/com/amazon/sampleapp/App.java, sample-apps/spark/src/main/java/com/amazon/sampleapp/MetricEmitter.java, sample-apps/springboot/src/main/java/com/amazon/sampleapp/DemoController.java, sample-apps/springboot/src/main/java/com/amazon/sampleapp/MetricEmitter.java
=> Update to otel 0.17.0

dependencyManagement/build.gradle.kts
=> Update to otel 1.0

awspropagator/build.gradle.kts, build.gradle.kts
=> Fix publishing of java-library and enable for propagator library.

dependencyManagement/build.gradle.kts, gradle.properties, instrumentation/log4j-2.13.2/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/log4j_2_13_2/AwsXrayLog4jInstrumentationModule.java, instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLogbackInstrumentationModule.java, instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLoggingEventInstrumentation.java, sample-apps/spark-awssdkv1/src/main/java/com/amazon/sampleapp/MetricEmitter.java, sample-apps/spark/src/main/java/com/amazon/sampleapp/MetricEmitter.java, sample-apps/springboot/src/main/java/com/amazon/sampleapp/MetricEmitter.java
Also adds missing gradle.properties
=> Update to otel 1.1.0

awsagentprovider/build.gradle.kts, dependencyManagement/build.gradle.kts, instrumentation/log4j-2.13.2/build.gradle.kts, instrumentation/log4j-2.13.2/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/log4j_2_13_2/AwsXrayLog4jInstrumentationModule.java, instrumentation/logback-1.0/build.gradle.kts, instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLogbackInstrumentationModule.java, instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLoggingEventInstrumentation.java, licenses/licenses.md
Updates upstream dependency and other build dependencies.
=> Update to OTel 1.2.0

dependencyManagement/build.gradle.kts, instrumentation/log4j-2.13.2/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/log4j_2_13_2/AwsXrayLog4jInstrumentationModule.java, instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLoggingEventInstrumentation.java, otelagent/build.gradle.kts
=> Update OTel to 1.3.1

.github/workflows/patch-release-build.yml
=> Sync patch release workflow with normal release.

build.gradle.kts
=> Allow releasing from release branch for patches.

awsagentprovider/build.gradle.kts, awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerConfigurer.java, dependencyManagement/build.gradle.kts, smoke-tests/runner/build.gradle.kts, smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/SpringBootSmokeTest.java
=> Wire up xray sampler.

dependencyManagement/build.gradle.kts, sample-apps/spark-awssdkv1/src/main/java/com/amazon/sampleapp/MetricEmitter.java, sample-apps/spark/src/main/java/com/amazon/sampleapp/MetricEmitter.java, sample-apps/springboot/src/main/java/com/amazon/sampleapp/MetricEmitter.java
=> Update to OTel 1.5

.github/collector/docker-compose.yml, .github/workflows/docker-build-corretto-slim.yml, .github/workflows/docker-build-smoke-tests-fake-backend.yml, .github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/release-build.yml, .github/workflows/soak-testing.yml
Reverts aws-observability/aws-otel-java-instrumentation#110
=> Revert "Use aws-credentials action to configure creds bc it uses OIDC by default"

dependencyManagement/build.gradle.kts
=> Update OTel dependency to 1.7.2

gradle/wrapper/gradle-wrapper.properties, settings.gradle.kts
=> Update Gradle and build dependencies.

sample-apps/spark-awssdkv1/src/main/java/com/amazon/sampleapp/MetricEmitter.java, sample-apps/spark/src/main/java/com/amazon/sampleapp/MetricEmitter.java, sample-apps/springboot/src/main/java/com/amazon/sampleapp/MetricEmitter.java
=> Try to workaround SDK synchronous counters not reported consistently.

dependencyManagement/build.gradle.kts
=> Update log4j test dependency

smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/LogInjectionTest.java
=> Reenable log injection test

.github/workflows/docker-build-corretto-slim.yml, scripts/docker/corretto-slim/Dockerfile
=> Update corretto base image to Java 17 and build for arm64 too.

otelagent/build.gradle.kts
This PR add arm support builds for base image
=> Add arm support builds for base image

.github/workflows/docker-build-corretto-slim.yml, .github/workflows/docker-build-smoke-tests-fake-backend.yml, .github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml, .github/workflows/patch-release-build.yml, .github/workflows/pr-build.yml, .github/workflows/release-build.yml
=> Update workflow JDK to 17 and use docker login action

dependencyManagement/build.gradle.kts
=> Update to OTel 1.10.1

gradle/wrapper/gradle-wrapper.properties, settings.gradle.kts
=> Update Gradle and build dependencies

sample-apps/spark/build.gradle.kts
This PR uncomments the `platforms` based changes to build spark app images to support multi arch,
=> Uncomment the `platform` changes for spark sample app builds to support multi-arch.

awsagentprovider/src/test/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerConfigurerTest.java
=> Add test for traceidratio sampler

settings.gradle.kts
=> Upgrade build dependencies

settings.gradle.kts
=> Update build dependencies

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md
Add best effort support policy
=> Add best effort policy to issue templates and readme

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Fix issue template

.github/workflows/docker-build-corretto-slim.yml, .github/workflows/docker-build-smoke-tests-fake-backend.yml, .github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml, .github/workflows/pr-build.yml, .github/workflows/release-build.yml
Adds workflow names to improve readability in GitHub UI. 
=> Add GitHub Action workflow names

.github/workflows/stale-bot.yml
This PR creates the Stale bot for the issues and PR
=> Create Stale Bot

.github/workflows/main-build.yml, .github/workflows/release-build.yml
Fix approval workflows that run integration tests so that they are configured correctly.
obs.: we don't need to run jib in the release workflow because we only publish images tagged with `latest` that are updated in the main-build workflow.
=> Fix approval workflows

.github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml
*Description of changes:* Emit metrics from github workflows
=> Emit metrics from github workflows

.github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml
Use correct role to publish metrics
=> Use correct role to publish metrics

.github/workflows/patch-release-build.yml
Description:
This PR updates the usage of set-output command in GH actions.
=> Update the usage of set-output command in GH actions

settings.gradle.kts
Reverts aws-observability/aws-otel-java-instrumentation#280
=> Revert "Bump org.springframework.boot from 2.7.5 to 3.0.0"

.github/workflows/main-build.yml
*Description of changes:* Fix typo in main-build
=> Fix typo in main-build

sample-apps/spark/src/main/resources/log4j2.xml
Reference PR : https://github.com/aws-observability/aws-otel-community/pull/107
Doc : https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-logging
=> Modify Log format to match with the service lens

.github/actions/patch-dependencies/action.yml, .github/scripts/patch.sh, .github/workflows/main-build.yml, .github/workflows/pr-build.yml, .github/workflows/release-build.yml, RELEASING.md
* Add new process for patch releases
---------
Co-authored-by: bryan-aguilar <46550959+bryan-aguilar@users.noreply.github.com>
Co-authored-by: Anthony Mirabella <a9@aneurysm9.com>
=> Backport to release/v1.21.x branch: Add new process for patch releases (#321)

build.gradle.kts
*Description of changes:* Add release pattern so that that we can release from release branches during patch procedure.
https://github.com/nebula-plugins/nebula-release-plugin
=> Add release release pattern

build.gradle.kts
* Add release release pattern
---------
=> Backport to release branch: Add release pattern (#324)

RELEASING.md, build.gradle.kts
*Description of changes:* Force usage of release branch during release process
=> Force usage of release branch during release process

.github/actions/patch-dependencies/action.yml
*Description of changes:* Backport https://github.com/aws-observability/aws-otel-java-instrumentation/pull/327
=> backport Cleanup patch repositories after build #327

.github/workflows/owasp.yml, otelagent/build.gradle.kts, settings.gradle.kts
Add dependency check based on OWASP using this gradle plugin: https://plugins.gradle.org/plugin/org.owasp.dependencycheck
=> Add workflow to run dependency check based on OWASP

.github/workflows/owasp.yml
*Description of changes:* Update workflows to the latest version and fix typo in properties.
=> Fix typo in owasp workflow

.github/workflows/patch-release-build.yml, .github/workflows/release-build.yml
Resolving error due to region in:
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/4704024997/jobs/8343220082
=> Resolving errors in region in workflow

README.md
*Description of changes:* Added a link in the README to the new standardized sample apps.
=> Add link to new sample apps

.github/workflows/codeql-analysis.yml, .github/workflows/docker-build-corretto-slim.yml, .github/workflows/docker-build-smoke-tests-fake-backend.yml, .github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml, .github/workflows/owasp.yml, .github/workflows/patch-release-build.yml, .github/workflows/pr-build.yml, .github/workflows/publish-status.yml, .github/workflows/release-build.yml, .github/workflows/soak-testing.yml
*Issue #, if available:* #398
*Description of changes:* Update actions to not use node 12.
Commits updated one component at a time to simplify the review.
=> Update workflows to use node 16

.github/workflows/patch-release-build.yml, .github/workflows/release-build.yml
*Description of changes:* Properly set the region
This was done in the release branch v.1.24.x but was not brought back into main.
=> fix release v1.26.x

.github/workflows/publish-status.yml
*Description of changes:* Fix typo in publish-status workflow
=> Fix typo in publish-status workflow

.github/dependabot.yml
*Description of changes:* Update scheduled day in dependabot.yml
=> Update scheduled day in dependabot.yml

.github/workflows/main-build.yml
*Description of changes:* small fixes in the main build workflow.
=> Fix: fix workflow

instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLoggingEventInstrumentation.java
*Issue #, if available:* #431
As described in the issue the `AWS-XRAY-TRACE-ID` MDC entry is inconsistent with the `trace_id` added by the [Logback MDC instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/logback/logback-mdc-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/logback/mdc/v1_0/LoggingEventInstrumentation.java).
The issues we experienced was that the first HTTP request handled on a thread, the `AWS-XRAY-TRACE-ID` MDC entry was not added. However for all subsequent requests handled on the same thread, they had the `AWS-XRAY-TRACE-ID` MDC entry for the first request.
The change to fix this was just to implement the same way of adding MDC entries as the [Logback MDC …
=> Fix inconsistent MDC entries for X-Ray trace-id (#431)

.github/workflows/main-build.yml, .github/workflows/pr-build.yml
Remake of #488 but push to main repo instead of fork.
=> [release/v1.28.x] Cache maven local

.github/workflows/main-build.yml
Make sure that batch jobs complete successfully before publishing status and use that job result in conditional.
=> [chore] Add batch job as requirement of status

.github/workflows/main-build.yml
Fix release v1.31.x annotation error in main-build workflow
=> Fix release v1.31.x annotation error in mainbuild workflow

.github/workflows/main-build.yml
Removing the used hardcoded image tag in e2e testing
=> Removing hardcoded image tag

.github/workflows/appsignals-e2e-eks-canary-test.yml, .github/workflows/appsignals-e2e-eks-test.yml
Updating canary rate to be every 15 minutes
Updating test metric to be failure instead of success
=> [App Signals] E2E Testing: Change canary rate, update test metric

.github/workflows/appsignals-e2e-eks-test.yml, .github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml
Reverts aws-observability/aws-otel-java-instrumentation#643
=> Revert "Provide aws-region for the e2e test in worklow"

.github/workflows/appsignals-e2e-ec2-test.yml
Dynamic input RPM link by region setting, noted that IAD have it's specific form of link
=> Dynamic input RPM link by region setting

.github/workflows/build-and-push-image-with-cpUtility-test.yml, .github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml
=> Adding missing symbols in workflows

.github/workflows/main-build.yml, .github/workflows/nightly-upstream-snapshot-build.yml
Fix for below error:
The workflow is not valid. .github/workflows/main-build.yml (Line: 118, Col: 9): Unexpected value 'secrets' .github/workflows/main-build.yml (Line: 153, Col: 19): Unrecognized named-value: 'env'. Located at position 1 within expression: env.AWS_DEFAULT_REGION
=> Fixing main build failure

.github/workflows/appsignals-e2e-ec2-test.yml, .github/workflows/appsignals-e2e-eks-test.yml
We need these test changes to validate release build.
```
git checkout release/v1.32.x 
git pull
git cherry-pick 90cd25d468e27546cf0756f1b88bdaa1dd68ccda
git checkout -b patch-test
git push -u origin patch-test
```
=> Update Release Testing with latest changes

CONTRIBUTING.md
Clarify expectations around PRs.
=>  Update CONTRIBUTING.md for PR best practices

.github/workflows/release-build.yml
Revert commenting out some of the release steps that were commented for doing a specific section of the release.
This was done in PR #847 
=> revert: Uncomment release steps that were commented in #847

.github/workflows/application-signals-e2e-test.yml
Updating the release testing workflow to point to the main branch now that the changes have been merged
Test run: https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/10063732660
=> Update consolidate release to main

.github/workflows/owasp.yml
=> Update owasp.yml to use new metrics role ARN

awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AttributePropagatingSpanProcessor.java
=> Add null checks

.github/workflows/application-signals-e2e-test.yml
Updated e2e test file name in this [PR](https://github.com/aws-observability/aws-application-signals-test-framework/pull/178)
Update the file names to point to the new ones
=> Update E2E File to new name

.github/workflows/e2e-tests-app-with-java-agent.yml
Follow up from https://github.com/aws-observability/aws-otel-java-instrumentation/pull/877, missed one.
=> Fix docker-compose

.github/actions/image_scan/action.yml, .github/workflows/owasp.yml, .github/workflows/pr-build.yml
Align with Python:
* https://github.com/aws-observability/aws-otel-python-instrumentation/blob/main/.github/actions/image_scan/action.yml
* https://github.com/aws-observability/aws-otel-python-instrumentation/blob/main/.github/workflows/daily_scan.yml
=> Replace OWASP workflow

.github/workflows/e2e-tests-with-operator.yml
Reverts aws-observability/aws-otel-java-instrumentation#883
=> Revert "Update e2e-tests-with-operator.yml"

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/base/ContractTestBase.java, appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/misc/RuntimeMetricsTest.java, appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/AppSignalsConstants.java, appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/utils/MockCollectorClient.java
N/A
This PR adds contract tests for runtime metrics feature, where it validates:
1. Are all runtime metrics captured?
2. Do the runtime metrics have a realistic value? (non-negative)
These changes can easily be extended for higher coverage in the future.
=> [DO NOT MERGE] feat: Add contract tests for runtime metrics

.github/workflows/owasp.yml
Final step of MCM:
https://mcm.amazon.dev/cms/MCM-112315558/execution/step/e035bb70-e64d-4aee-a26f-ac4c2c11c029
=> Update image scan workflow for v1.32.4

.github/workflows/owasp.yml
Update image scan to ADOT Java v1.32.5.
=> Update image scan to 1.32.5

.github/workflows/application-signals-e2e-test.yml
Missed this part in the previous PR for E2E testing.
=> Add java lambda e2e test case

.github/workflows/release-lambda.yml
Decision from an internal discussion.
=> support java11 runtime for lambda

.github/workflows/owasp.yml
Use v2.0.0 in the v2 release branch.
=> Upgrade image scan to use v2.0.0 in v2 release branch

.github/workflows/release-build.yml, .github/workflows/release-lambda.yml
Same as: https://github.com/aws-observability/aws-otel-python-instrumentation/pull/335 and https://github.com/aws-observability/aws-otel-python-instrumentation/pull/337
=> Update SDK and Lambda Layer Release Workflows to Add layer.zip Artifacts

.github/workflows/owasp.yml
Update Image Scan version to v2.0.1 for v2
=> Update Image Scan version to v2.0.1 for v2

.github/patches/opentelemetry-java-instrumentation.patch, dependencyManagement/build.gradle.kts, licenses/licenses.md
=> Release ADOT Java v2.0.1

appsignals-tests/contract-tests/src/test/java/software/amazon/opentelemetry/appsignals/test/base/ContractTestBase.java, awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsApplicationSignalsCustomizerProvider.java
add default values for env variable if not set for non lambda env
=> add default values for env variable if not set

.github/actions/execute_and_retry/action.yml
Add the custom retry GH action 
=> Add the custom retry GH action 

.github/workflows/owasp.yml
A followup fix for https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1061
=> Formatting the retry command for custom retry action

.github/workflows/application-signals-e2e-test.yml, .github/workflows/main-build.yml, .github/workflows/pr-build.yml, .github/workflows/release-lambda.yml, lambda-layer/build-layer.sh, lambda-layer/build.gradle.kts, lambda-layer/otel-instrument, lambda-layer/patches/StreamHandlerInstrumentation.patch, lambda-layer/patches/aws-otel-java-instrumentation.patch, lambda-layer/patches/opentelemetry-java-instrumentation.patch
This PR changes mainline and upgrades the Java Lambda Layer to **2.10.0** and migrates the Lambda Layer build code in the 1.33.x release branch to main branch.
1. Changed the build-layer.sh to also apply patching from current ADOT SDK in `.github`
2. Added the lambda build step to the main and pr build workflows.
3. Added `StreamHandlerInstrumentation.patch` patching file to pulled from release/v1.33.x
4. Removed Active span linking tracing from patches as this has already been applied to upstream: https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/d7e909879a77f860396705b01f7f69eef356f011#diff-219664837e8bb1881334baba6fae9fa9c4980557d7307552bbfa93e29ace75fc
5. Removed SQS span linking as this is already handled by …
=> Upgrade Java Lambda Layer to 2.x

.github/workflows/release-udp-exporter.yml, exporters/aws-distro-opentelemetry-xray-udp-span-exporter/CHANGELOG.md, exporters/aws-distro-opentelemetry-xray-udp-span-exporter/build.gradle.kts
=> Prepares X-Ray UDP Exporter v1.0.0 release

.github/workflows/owasp.yml
Update owasp.yml to scan 2.11.2 release.
=> Update image scan to point to 2.11.2 release

.github/workflows/owasp.yml
Update owasp.yml to scan 2.11.4 release.
=> Update owasp.yml to scan 2.11.4 release

.github/workflows/daily-scan.yml
=> Update image to 2.11.5 in daily-scan.yml
